### ISSUE TITLE
guild invite/guild ally add improvements

### ISSUE THREAD

**Issue by madtomic** [guilds-plugin/Guilds#100]
instead of typing commands in chat. let's player click to accept / decline in chat to join guild.

This can also be use to improve guild ally add command.

This is borrow from Clans.
![image](https://user-images.githubusercontent.com/6004542/53462115-b0b43a80-3a10-11e9-88bd-cc7f04995f6a.png)

**Comment by darbyjack** [comment]
I'm going to close this because I approached this in a different way. You now get provided a custom tab completed list depending on your guild for the options.
