### ISSUE TITLE
Guild Vault Improvement

### ISSUE THREAD

**Issue by madtomic** [guilds-plugin/Guilds#101]
Improve guild vault size based on guild tier.

/guild vault - 1st vault
/guild vault 2 - 2nd vault
/guild vault 3 - 3rd vault
etc,

```java
tier1:
  name: "Bronze"
  cost: 0
  max-members: 15
  mob-xp-multiplier: 1
  damage-multiplier: 1
  max-bank-balance: 10000
  **max-guild-vault: 1**
  members-to-rankup: 0
  permissions:
  -
```

**Comment by darbyjack** [comment]
![uabLd2024x15530611612019](https://user-images.githubusercontent.com/21014720/54662236-63753700-4aab-11e9-8adb-cb74bdeb0196.gif)
Here's my progress on it so far!

**Comment by darbyjack** [comment]
This feature has been completed and will added into the next update!

**Comment by HauserGrim** [comment]
up :)

**Comment by darbyjack** [comment]
Not happening until they come up with a system to support current data and how it might disappear.
