### ISSUE TITLE
Tier extra permissions not* working

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#106]
Server ver: latest paper 1.13.2
Plugins: vault, guilds, essentialsx (chat, spawn). All latest from spigotmc
Config: default

I add to tier1 permissions, reload config and create guild

  permissions:
  - "guild.commands.reload"
  - "essentials.gamemode"
  - "essentials.gamemode.all"

and player still does not have permission
I tried without quotes or add a couple of spaces in front of "-" but nothing worked.

**Comment by darbyjack** [comment]
Fixed!
