### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by Basketcaisse21** [guilds-plugin/Guilds#108]
![Capture](https://user-images.githubusercontent.com/1885357/55340767-54ab5e80-5473-11e9-9a65-8212f1aace75.PNG)
I noticed no matter what command I type, as long as I don't complete it, it shows "- Showing page 1 of 5 (48 results)."

**Comment by darbyjack** [comment]
This is fixed now. Thanks for pointing that out.
