### ISSUE TITLE
Guild Sethome error

### ISSUE THREAD

**Issue by Basketcaisse21** [guilds-plugin/Guilds#109]
Everytime I attempt to set a home for my guild using the /guild sethome command the game tells the client "I'm sorry, but tere was an error performing this command." and in the console it kicks back this error.

https://pastebin.com/b9jbNuZK

**Comment by Basketcaisse21** [comment]
After more digging, I learned that you need to claim land before using the sethome command. Perhaps throwing an error message up will resolve this issue.

**Comment by darbyjack** [comment]
Claims have nothing to do with setting a home. It's probably a bug I'll fix in the beta.
