### ISSUE TITLE
Claiming with Wands - By Price / Limit

### ISSUE THREAD

**Issue by RumiExMachina** [guilds-plugin/Guilds#120]
## Context

I'm looking for a new Land Claiming plugin that has WorldGuard as a base.
The current claiming system is awesome, but I wanted something more, like a Wand to select claims and ways to subdivide the claim into smaller zones.

A way it would benefit other users is that the plugin will become more versatile in the field of survival servers. Allowing server owners to manage land easily.

## Possible Implementation

I really don't know how hard it would be to implement, but I belive it's possible with WorldGuard API.

**Comment by darbyjack** [comment]
I've decided to close this issue because WorldGuard claims will become obsolete in the next month or two when I complete the new claiming system.
