### ISSUE TITLE
Guild Prefix Brackets [ ]

### ISSUE THREAD

**Issue by merlinshaw** [guilds-plugin/Guilds#140]
It would be nice to be able to make any type of brackets around guild prefixes for essentials chat.
So if your guild prefix was Boop in essentials chat it would be [Boop]. and being able to add color codes to it as well.

**Comment by madtomic** [comment]
I think you can already do this in Essentials chat.
```java
&7[{GUILDS}&7]
```

**Comment by merlinshaw** [comment]
That is very true. But some user do not want guilds and having a random [] in front of their prefix bugs me and them.

**Comment by good3n** [comment]
@merlinshaw There could be a workaround depending on the chat plugin you're using. For example, in Guilds, guild members can have a permission node's assigned to them based on tier. I have `guild.level.*` (* represents the tier level). Then, in my chat plugin, I have it formatted that anyone with that permission, their chat is formatted to use the Guild prefix.

For reference I use chat control pro.

**Comment by merlinshaw** [comment]
I see. Why go through all the trouble if it can just be added to the plugin to allow them? Seems a lot simpler. Then to make work arounds for the end user.

**Comment by good3n** [comment]
Well, it’s not trouble at all. Guilds has features built into it that allow you to do exactly what you’re asking. It sounds like a feature request you should be requesting on your chat plugin’s repository.

**Comment by merlinshaw** [comment]
I'm using Essentials Chat.  I have given permission to everyone to be able to create a guild. Very few people want a guild and just want to play solo. So i have the chat formatted as so.
  format: '{GUILD_PREFIX}{DISPLAYNAME}&6‡&f {MESSAGE}'
It works but when it comes down to visuals it would be nice to have a bracket around them. So in chat it shows up as.

[Guild] [Server Rank] Username: 

But as it is now its
Guild[Server Rank] Username:

If i go into Essentials and add brackets around {GUILD_PREFIX} It show up like this.
  format: '[{GUILD_PREFIX}]{DISPLAYNAME}&6‡&f {MESSAGE}'
[Guild] [Server Rank] Username: 

But for people not wanting a guild they have this.
[] [Server Rank] Username: 
Pointless brackets in front of their rank

It would be nice to be able to in config to add type of brackets you want to use for the left and right side. and to choose the default color of those brackets. Something like this in the config.
  bracket:
    color: &6
    left: "["
    right: "]"
  guild-prefix:
    color: &a
 guild-name:
    color: &a

This would allow the serve rowner to change the default color of the guilds name and prefix along with add brackets that they choose.

**Comment by darbyjack** [comment]
That kind of configuration for handling Essentials is a bit much. I can make it that intensive but it won't be ready for 3.4.7. It'll probably be a 3.4.8 feature if you want it that in-depth.

**Comment by merlinshaw** [comment]
It does not have to go that in depth it was just a way of explaining. just to be able to make my own brackets would be nice like here in the config if we were able to add them in to this spot
guild:
    requirements:
        name: '[a-zA-Z0-9&]{1,64}'
        prefix: '[a-zA-Z0-9&]{1,20}'

**Comment by darbyjack** [comment]
I could give a simple option to add brackets into the placeholder. I might be able to allow the color of the brackets but probably won't go as in depth as you had it.

**Comment by darbyjack** [comment]
Actually, what are your thoughts on an option to return when it's empty? So like it could return EMPTY or NONE or whatever you choose to display.

**Comment by darbyjack** [comment]
Actually, I just came up with this idea. 
![image](https://user-images.githubusercontent.com/21014720/57987761-cd7a7000-7a4b-11e9-9b28-10340d425f6e.png)

**Comment by merlinshaw** [comment]
So how would that work? This is my essentials format how will it tell one bracket from the other?
format: '{GUILD_PREFIX}{DISPLAYNAME}&6‡&f {MESSAGE}'

**Comment by darbyjack** [comment]
Ahh then I have no idea. I have it just checking [] around the guild placeholders for your chat format.

**Comment by good3n** [comment]
@merlinshaw Can't you do permission based chat formatting with Essentials Chat?

**Comment by madtomic** [comment]
How about just use the group chat format in essential chat and simply leave out the {guild} for anyone don’t want to join a guild. You only have to give that solo player the essential chat group permission and it is done.

**Comment by merlinshaw** [comment]
So you're saying make a chat format for each rank.  I have in my permissions? By default I want everyone to have the option to make a guild if they wish. They way my group manager perms are set up it would not work that way. 

The current implementation is a step in the right direction.  I'm hoping @darbyjack will keep it in mind and maybe fix it up more later on.

Also if you look into the old plugin called simpleclans he used the same thing for brackets as I was suggesting. And it worked perfectly.  Should be able to see how it was done on his github.

**Comment by darbyjack** [comment]
```YAML
        # Used for the following placeholders: guild_name_formatted, guild_prefix_formatted
        placeholder-design:
          # The left bracket in the placeholder
          left-bracket: "["
          # The guild name in the placeholder
          name: "{name}"
          # The guild prefix in the placeholder
          prefix: "{prefix}"
          # What to show instead of the placeholder if there's no guild
          no-guild: ""
          # The right bracket in the placeholder
          right-bracket: "]"```

Proposed fix. Thoughts?
