### ISSUE TITLE
Buyable region with signs ?

### ISSUE THREAD

**Issue by Daxxas** [guilds-plugin/Guilds#142]
## Context
Adding buyable predefined regions where you need to pay with the bank's account would let servers have claimable area for guilds without having to have an infinite world where player have to claim here. 
It would let servers have a way to use guilds that is less PvP driven and more Community driven.

## Possible Implementation
An admin would define a WorldGuard region, and with Guilds put it on sale, and adding a sign would be optional

**Comment by darbyjack** [comment]
Really interesting suggestion! I'll see what can be done for a future update.

**Comment by damianmakkink** [comment]
Totally supporting this idea! This also opens up the possibility to let guilds buy premade 'guild houses', as we see in many MMORPG's.

**Comment by Daxxas** [comment]
Haha, thanks you man 👍

**Comment by darbyjack** [comment]
@Daxxas @damianmakkink This has been implemented for the update coming today or Tomorrow.
