### ISSUE TITLE
Bug - guild masters don't have permission to add ally

### ISSUE THREAD

**Issue by madtomic** [guilds-plugin/Guilds#144]
It should be default feature for guild masters.

Unless, the guilds have to be public guilds?

![image](https://user-images.githubusercontent.com/6004542/57930060-fbf91f00-7882-11e9-8526-a84faddf3557.png)

**Comment by darbyjack** [comment]
![image](https://user-images.githubusercontent.com/21014720/57942376-e7268680-7896-11e9-9c96-11ef816ebafb.png)
Can't reproduce. It's /guild ally add

**Comment by madtomic** [comment]
No args after add?

**Comment by darbyjack** [comment]
No, it's not a GUI. If you type in /guild ally add, it'll show you in the tab list which Guilds you can send a request to.

**Comment by madtomic** [comment]
Gotcha
