### ISSUE TITLE
Disable Prefix Option

### ISSUE THREAD

**Issue by SirGoldman-git** [guilds-plugin/Guilds#148]
Prefixes will never be needed on my setup, I cant deny the perm `guilds.command.prefix` to disable it due to it being in the /g create command. A option in the config to disable it would be nice!

**Comment by darbyjack** [comment]
Should be added for the next update. https://github.com/guilds-plugin/Guilds/commit/46c9a097cbe6df3ab61e208c1dfe79087a4174ae

**Comment by SirGoldman-git** [comment]
You're awesome, thank you!
