### ISSUE TITLE
GUI Requests

### ISSUE THREAD

**Issue by SirGoldman-git** [guilds-plugin/Guilds#149]
Can you please hide the iron helmet tool tip in /g info (When on head: Does this): https://gyazo.com/6eb033b1b29a9e9489d0f5b6752c0f8d

Also, can you rename the glass panes to "&r" so it doesn't display the glass name.

* Guilds version: 3.4.6-RELEASE
* MC Version: Spigot 1.14.1

**Comment by darbyjack** [comment]
I don't understand what you mean.

**Comment by SirGoldman-git** [comment]
`ItemFlag.HIDE_ATTRIBUTES`

**Comment by darbyjack** [comment]
Should be good now!
