### ISSUE TITLE
Money Format

### ISSUE THREAD

**Issue by SirGoldman-git** [guilds-plugin/Guilds#150]
Can you add commas in the values, like this: https://gyazo.com/2598bd391710889825f3852d1b9beed6

**Comment by darbyjack** [comment]
I think what I just pushed should handle it. It'll auto format it to use commas! If you're satisfied with that, feel free to close this issue!

**Comment by SirGoldman-git** [comment]
I'm working atm but I will check it out soon! Thank you!!!

**Comment by darbyjack** [comment]
No rush! I'm headed to bed so you can let me know here or on Discord. Hopefully, I didn't keep you waiting too long on these fixes. I was moving the past day and a half and didn't even set up my computer until this morning.

**Comment by SirGoldman-git** [comment]
Where can I find the download to the fixed jar?

**Comment by darbyjack** [comment]
It'll be live once I release the update or you can compile it yourself.

**Comment by SirGoldman-git** [comment]
I complied the v3.4.7-BETA of Guilds, booted fine, libs updated but none of the stuff I reported was resolved, still getting click event error on creation of the vault and amounts still dont have commas: https://gyazo.com/72a0f18b88e0890eecb97a5030a34209 (Maybe you didn't push yet?)

**Comment by darbyjack** [comment]
Make sure you built the right branch. The fixes on are v3.4.7 and not master yet.
