### ISSUE TITLE
Displayname Support

### ISSUE THREAD

**Issue by SirGoldman-git** [guilds-plugin/Guilds#151]
Can you please make it possible to display a player's displayname in `/g chat`? (Nameplate or Nick Support) :)

**Comment by good3n** [comment]
Think you can use Placeholder API.

**Comment by SirGoldman-git** [comment]
Nice, didn't know if chat supported placeholderAPI, will check later today.

**Comment by darbyjack** [comment]
I think what I just pushed should handle it!
