### ISSUE TITLE
Guild MOTDs

### ISSUE THREAD

**Issue by darbyjack** [guilds-plugin/Guilds#153]
## Context

Allow for the use of having MOTDs that each Guild can set for their users.

## Possible Implementation

- /guild motd set
- /guild motd remove
- /guild motd (that would probably just view it)
- /guild admin motd set <guild> <message>
- /guild admin motd remove <guild>

Then players could toggle if they want to see it or not. This could probably also go in the guild info GUI.

**Comment by supertakeru** [comment]
This looks good as you could set up news, objectives, etc in the form of an MOTD for guilds.

**Comment by darbyjack** [comment]
Exactly. It'd be part of a role and then the owner can set up which roles can handle it.

**Comment by darbyjack** [comment]
Great progress has been made so far on this! All that is left is to fix a null check for the info GUI and then make it send a message to the player a few seconds after they login.
