### ISSUE TITLE
PvP trident bow bug + flag

### ISSUE THREAD

**Issue by Gorderok** [guilds-plugin/Guilds#163]
The pvp between members or allies is not blocked if it is damaged by a bow or a trident. 

Is it possible to have a flag allowing damage between members? Where can I disable the plugin on other worlds? This worries me for pvp events on another world.

**Comment by darbyjack** [comment]
You can already modify in the config the ability for guilds and allies to damage to each other.

**Comment by Gorderok** [comment]
Yes I know, the damage is disabled. The problem is for event worlds for example. I can not activate pvp on this world.
        guild: false
        ally: false
        respect-wg-pvp-flag: false
How to have pvp between members / alliances on one world and not on another?

**Comment by darbyjack** [comment]
You can't.
