### ISSUE TITLE
Autoflags for guild claims

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#165]
Many use autoflag plugins for wg, which is inconvenient when it doesn’t work for guild claims.

config option:
claims:
    flags:
        pvp: DENY

**Comment by darbyjack** [comment]
I have no idea what an auto flag is. Please elaborate.

**Comment by HauserGrim** [comment]
When a player creates a claim, some flags are automatically set.

**Comment by darbyjack** [comment]
What kind of flags you want?

**Comment by HauserGrim** [comment]
In fact, I don’t need anything other than the pvp flag to disable all pvp on claim.
Many things that are necessary for me are blocked by third-party plugin, but I think that such flags as tnt, greeting / farewel, enderpearl, chorus-fruit-teleport, maybe some flags from WorldGuard Extra Flags

I do not think that all my words are translated correctly, I can only say that this is rather a pleasant bonus than a necessity.

**Comment by darbyjack** [comment]
I'm closing this issue for now because I am going to mark it as a duplicate for #172 as I plan to implement this into it.
