### ISSUE TITLE
Pay with guild money

### ISSUE THREAD

**Issue by Gorderok** [guilds-plugin/Guilds#175]
It would be a good idea to add an order to pay with guild money. Example:  /guild pay 1000
it would take money directly to the guild bank

**Comment by darbyjack** [comment]
How would this be used?

**Comment by Gorderok** [comment]
We could link the command to other plugins (quest, seller etc)
This would execute an order: /g pay <amount>
And the money would be deducted from the bank

**Comment by KissOfFate** [comment]
@Gorderok When you mean `/g pay amount` do you mean to be able to pay other guilds or people? 

If so should you only be able to pay guild members? or should it be configurable to let certain roles pay outside of your guild.

NPCs and Quests should use the `/g admin bank withdraw <amount>` command.

**Comment by Gorderok** [comment]
My idea was no longer a command like what you explain: / g admin bank withdraw <name> <amount>

The idea of ​​having the / g pay amount configurable to pay members or outside can also be very useful!

**Comment by wolfebersahd** [comment]
This is simply a shortcut from doing `/guild bank withdraw <amount>` followed by `/pay <player` it's 1 extra command.

And in the case of NPCs ot shops just make sure you have enough in your player wallet with `/guild bank withdraw <amount>` before clicking on said NPC.

**Comment by Gorderok** [comment]
Hi, do you know when this feature will be implemented?

**Comment by darbyjack** [comment]
I have no plan to add this at this point in time.

**Comment by Gorderok** [comment]
Do you intend to add useful things? There have just been fixes for 1 year.

**Comment by darbyjack** [comment]
That statement couldn't be further from the truth. 
Just to list a couple things over the past year:
1) 5 new languages supported
2) New buff system
3) New role system
4) Almost completed new claim system
5) Numerous commands added

Just because the one thing you ask for isn't added doesn't justify you to say something like that. The project is open source, add it yourself. It takes maybe 10 minutes max to do so.

**Comment by Gorderok** [comment]
Yes, nothing new. Sad, where are your early ideas?

**Comment by darbyjack** [comment]
As stated, the project is open source, you're welcome to add anything you'd like to it for your server.

**Comment by wolfebersahd** [comment]
@Gorderok

As KissOfFate mentions if you want the command to be executed in third party plugins like Quests or Sellers, etc. you could use:
```
/g admin bank withdraw <name> <amount>
/g admin bank deposit <name> <amount>
```

If you want to execute it in order to pay or reward other players, it's two commands as I mentioned:
```
/guild bank withdraw <amount>
/pay <player> <amount>
```
