### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by Daxxas** [guilds-plugin/Guilds#179]
## Context
This could let guilds have a discord channel for themselves and other maybe ?

## Possible Implementation
Players could get a role on discord when they join a guild in minecraft.
Servers could be able to set a category (in discord) where channels are created for guilds

I don't think this is really urgent, but it could be a nice feature to have :)

**Comment by darbyjack** [comment]
This was in a single release and the feedback was terrible, probably will not happen again any time soon.
