### ISSUE TITLE
Custom items & lore not supported in guild vault

### ISSUE THREAD

**Issue by Daxxas** [guilds-plugin/Guilds#185]
## Description
I know I already made an issue for this, but it got closed and I want to put a gif this time to prove it!

## Expected Behavior
We should be able to put custom items in the guild's vault

## Actual Behavior
Items with lore are considered as blacklisted items

## Possible Fix
I don't know the reason of the bug :(

## Steps to Reproduce
Try to put an item with a simple lore in a guild vault

## Context
Here is a gif to prove my problem : https://i.imgur.com/gELSDHy.gif
And here is my config about the blacklist : https://pastebin.com/EutqtkxP (it's the default one)

## Your Environment

* Guilds version 3.5.0
* MC Version 1.13.2

**Comment by darbyjack** [comment]
May I please get a list of your plugins so that I can try to reproduce this? Also, what plugin was used to change the lore of the item?

**Comment by Daxxas** [comment]
I used itemizer for the simple lore https://www.spigotmc.org/resources/itemizer.14733/
And the axe is a MythicMobs item.
I tried with a item that I gave myself with a command block to see if it's because of the itemizer plugin, but the problem is still here : https://puu.sh/DH63o/243fb4249c.gif
Idk what to send you for the plugin list, do you need a .zip with all the jar ? or a list is okay ?
Here is my plugin list anyway
`Plugins (51): PlaceholderAPI, MinewebBridge, SuperTrailsPro, ConsoleSpamFix, Core, MobFarmManager, EasyBackupCore, LuckPerms, Itemizer, WorldEdit, Skript, Stellyos, QuickBoard, EasyBackup, ProtocolLib, Multiverse-Core, LibsDisguises, TutorialCreator, AsyncWorldEdit, FastAsyncWorldEdit, DeACoudre, ActionAnnouncer, HoloDrops, Vault, CrazyCrates, MarketPlace, WorldGuard, Spleef, Multiverse-NetherPortals, MyCommand, TNTRun_reloaded, AreaShop, Guilds, MMOItems, BuycraftX, Citizens, MMOItemsAnyItemUpdater, DiscordSRV, AdvancedAchievements, MiniaturePets, BuildBattle, MythicMobs, GuildContracts, Bank, MythicMobsExtension, Jobs, DungeonsXL, CMI, MythicArtifacts, EpicCraftingsPlus, AdvancedEnchantments
`
