### ISSUE TITLE
Colors Included in Guild Name

### ISSUE THREAD

**Issue by seadoggie01** [guilds-plugin/Guilds#188]
## Description
The colors appear to be included in the guild name, causing players to not be able to join guilds.

## Expected Behavior
The colors should appear before the guild name

## Actual Behavior
There is an error saying that the guild doesn't exist

## Other
See https://discordapp.com/channels/390942438061113344/493935623925923841

(On behalf of Keizu, you said you would include in 3.5.1)

**Comment by darbyjack** [comment]
Fixed!
