### ISSUE TITLE
World whitelist 

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#191]
I use the DungeonsXL plugin for several dungeons and pvp games.
I'm afraid that players from the same guild or alliance will not be able to attack each other, thereby breaking the game mode.

Add whitelist for worlds in which guilds or pvp defense and buffs work.
Whitelist because DungeonsXL for sessions uses the name of worlds in order from DXL_Game_0 to DXL_Game_x

I think it will also help servers with minigames on the same server.

By default, in whitelist will have world, world_nether and world_the_end

I know my English is bad. Ask questions if something is not clear.

**Comment by KissOfFate** [comment]
So you mean you would like a blacklist of worlds where players can damage each other and buffs cannot be used/applied?

**Comment by HauserGrim** [comment]
No, there will be worlds in the white list, in which Guilds works 100%, while in the rest of the worlds there should be no influence of guilds, ally, buffs.

I see no other options to organize pvp between members same guild in another world, whose name (world) may change

**Comment by KissOfFate** [comment]
Ah alright, I understand, thank you for clarifying.
