### ISSUE TITLE
Damages of a player are rounded down 

### ISSUE THREAD

**Issue by Daxxas** [guilds-plugin/Guilds#199]
## Description
A golden shovel for example does 2.5 damages, but when you hit a mob you will only deal 2 damages. This can problematic on servers with custom weapons who can have like 10.94 damages or 8.04 for example.

## Expected Behavior
I should deal 2.5 damages with a golden shovel

## Actual Behavior
I deal 2 damages with a golden shovel

## Steps to Reproduce

1. Give yourself a golden shovel
2. Hit another player without armor
3. Look at the life he losts 

Be careful with minecraft's health, 0.5 health is actually 1/4 heart and not 1/2 heart

## Context
My server have random generated weapons with random damages, this is problematic that a weapon who have 10.01 damages and another one who have 10.99 damages does the same amount of damages

## Your Environment

* Guilds version 3.5.0 RELEASE
* MC Version 1.13.2
* Plugin List //

**Comment by darbyjack** [comment]
You're 2 versions behind. Please update and try again.

**Comment by darbyjack** [comment]
Fixed.
