### ISSUE TITLE
Back Buttons in menus

### ISSUE THREAD

**Issue by wildcore71** [guilds-plugin/Guilds#202]
## Context

It is a Very small hassle to close every gui and then redo /guild info

Ease of access! 💯 
## Possible Implementation

Add a Back Button in the Following Menu's
Guild Player List
Guild Vault's 
Vault Menu once opened <--Big One Here

**Comment by darbyjack** [comment]
So while I like this idea, I do have a single question which has prevented me from already implementing this.

There is more than one way to get to some of the GUIs and without doing a lot of stuff that may get messy, how would I know how they got into it?

If you guys were okay with the back button always going back to the same place, then I would be fine with that.

For example:

You can get to the list of members from the List GUI and the Info GUI.

**Comment by wildcore71** [comment]
I would see no issue with a back button in the menus that just takes you to
/guild info page. I think that's the main guild gui

**Comment by darbyjack** [comment]
Awesome, it'll be added into a future update.

**Comment by darbyjack** [comment]
Implemented in #207
