### ISSUE TITLE
Missing Language Key Error

### ISSUE THREAD

**Issue by beratakdas** [guilds-plugin/Guilds#216]
![Adsız](https://user-images.githubusercontent.com/50475184/62824594-12c0c080-bba9-11e9-8eea-a78d5b84ecef.png)

I'm getting this error. Plugin version: 3.5.2.6

**Comment by darbyjack** [comment]
![image](https://user-images.githubusercontent.com/21014720/62826700-9bc60080-bb85-11e9-9967-461a65942640.png)

**Comment by beratakdas** [comment]
Still same. It's not about language yml files. There is a issue uppercase/lowercase transformation. Plugin looking for confırm.error not confirm.error. Makes dotless letter (I / i).

**Comment by darbyjack** [comment]
What language are you trying to use?

**Comment by ruddeTR** [comment]
Its not Guilds's fault. Use UTF-8 in notepads and you can add those flags to your server's run code:
`
-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Duser.language=EN -Duser.country=US
`
