### ISSUE TITLE
A few requests.. :)

### ISSUE THREAD

**Issue by zStian** [guilds-plugin/Guilds#229]
I've got a few requests
* Playerheads in guild player list
* add {loser} as clan war placeholder
* add placeholder to vault GUI item titles
* set a message to '' without the extra space (hide lore or titles entirely)

**Comment by darbyjack** [comment]
In the future, please split them up so I can keep track of them easier. I've already implement the second one. The first one probably won't be possible for awhile. I have no idea what you mean by two and three. We have a template for a reason.
