### ISSUE TITLE
Invite players only to the same group for races

### ISSUE THREAD

**Issue by xespia** [guilds-plugin/Guilds#235]
## Context

My server use races plugin 
> https://www.spigotmc.org/resources/%E3%80%8Craces-of-thana%E3%80%8D%E3%80%8Cnew-1-13-update-custom-gui-races-day-night-effects-commands%E3%80%8D.59110/

A & B & C races are team 1, D & E & F races are team 2.
server main contents is 'Team 1 vs Team 2' 
I want Team 1's guilds, Team 2's guilds. so i want the feature to invite only people from the same group. If this feature is added, i will buy it right away.

It will benefit people who use the RPG Races plugin.

## Possible Implementation

config setting add
only-same-group-invite-and-join = true/false
1. Player A permission group is 'Human'.
2. Player A create guilds. Next add required group {permission group name}.
3. Check the group when invite or join guilds.

**Comment by darbyjack** [comment]
I have decided not to add this.
