### ISSUE TITLE
Member List Command

### ISSUE THREAD

**Issue by DeniedINC** [guilds-plugin/Guilds#248]
__**Why is this change important to you? How would you use it?**__
This is important for me because it allows me to create my own GUI with all of the same features and more for the guilds.

__**How can it benefit other users?**__
Other users would be able to do the same and have npc's like a Guild Master open the member list.

**Comment by darbyjack** [comment]
Implemented with https://github.com/guilds-plugin/Guilds/commit/ee1fa46d442ae7a2380fa9918677c317df828908
