### ISSUE TITLE
Feature Request: split up admin permissions 

### ISSUE THREAD

**Issue by xSolum** [guilds-plugin/Guilds#249]
I would like to request that you split up admin permissions into separate nodes to make it easier to manage staff permissions.

the guild chat spy permission in particular is a bit of an issue for me as I would like moderators to be able to see guild chat without giving them control over the entire plugin

**Comment by darbyjack** [comment]
Implemented in https://github.com/guilds-plugin/Guilds/commit/2c8027a630b851643194820b0fe7f99df33c2221
