### ISSUE TITLE
[Feature Request] Guild Guards

### ISSUE THREAD

**Issue by Antonelloh** [guilds-plugin/Guilds#252]
Possibility of having guards defending their guild from enemies and being upgradeable, this feature would be useful to people because so while you are offline there is someone to defend.

Sorry if my english is bad, but, i'm italian.

**Comment by darbyjack** [comment]
While I like this idea, I've decided not to. This would require hooking into another project for the NPCs (as I don't really want to make them myself) but if I ever change my mind, I will re-open this suggestion.
