### ISSUE TITLE
Guild vaults swallow items

### ISSUE THREAD

**Issue by xSolum** [guilds-plugin/Guilds#253]
## Description
If you place an item into the menu where you select guild vaults, closing the menu deletes the item

## Expected Behavior
I would expect to be unable to move or place inventory items within that GUI

## Actual Behavior
you can drop inventory items into the GUI

## Possible Fix
make it impossible to move items within the guild vault selection GUI

## Steps to Reproduce
1. open the guild vault GUI - /guilds vault
2. drag an item from your inventory into an empty slot
3. close the GUI
4. *the item is gone*

## Context
People make mistakes thinking that this GUI is their guild vault when their guild rank is unable to access guild vaults and lose items to it

## Your Environment
latest version

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/tree/4679de952868a3637436463e248bf087b82a1415
