### ISSUE TITLE
/guild admin tranfer <guild name> <playername> doesn't work and spits out a huge error report

### ISSUE THREAD

**Issue by wolfebersahd** [guilds-plugin/Guilds#261]
## Description
Using tab complete or manually writing in the players name spits out a huge error in console and in game.

## Expected Behavior
Guild should be transferred successfully.

## Actual Behavior
Error spammed in game and in console>
Console Error
https://pastebin.com/HN69X4wL
In game Error
![Capture](https://user-images.githubusercontent.com/9948243/68258782-d1a04700-0005-11ea-94db-f3593ae38d36.PNG)

## Steps to Reproduce

1. Create a Guild
2. Use admin command `/guild admin transfer` to transfer the guild
3. Use tab-complete for player name or manually write it

## Your Environment

* Guilds version: Latest 3.5.3.7
* MC Version: Paper 1.2.2
* Plugin List <prefer not to say :wink:

**Comment by darbyjack** [comment]
Fixed https://github.com/guilds-plugin/Guilds/commit/ccadd31068698afe29f4f7fbdd4de19144a428de
