### ISSUE TITLE
Insufficient permissions for `/guilds motd set` regardless of rank and permissions.

### ISSUE THREAD

**Issue by wolfebersahd** [guilds-plugin/Guilds#262]
## Description
When using `/guild motd set` the user gets "I'm sorry but you do not have permission to perform this command" regardless of guild rank. When the user is OPed, he gets "Your role is not high enough to do that"

## Expected Behavior
Guild masters and allowed roles should be able to successfully edit the MOTD with `/guilds motd set`

## Actual Behavior
Users are prohibited from changing the MOTD with the command, even when OPed.
![Capture](https://user-images.githubusercontent.com/9948243/68313991-79a82580-0083-11ea-8d7c-2ea9ffd91fa3.png)

## Steps to Reproduce

1. Create a guilds
2. Execute `/guilds motd set <some message`

## Your Environment

* Guilds version: Latest build 3.5.3.7
* MC Version: Paper 1.12.2
* Plugin List: I'd rather not say 😉

**Comment by darbyjack** [comment]
Should be fixed with https://github.com/guilds-plugin/Guilds/commit/0fee0442f59d93ae4aa6b0485b25d7e37a7a060a

**Comment by wolfebersahd** [comment]
I can confirm it's fixed in 3.5.3.8.
