### ISSUE TITLE
Can't damage MythicMobs when inside a guild.

### ISSUE THREAD

**Issue by wolfebersahd** [guilds-plugin/Guilds#264]
## Description
As per **Piedrops** can't damage MythicMobs when in a guild.

## Expected Behavior
MythicMobs can be damage when inside a guilds.

## Actual Behavior
MythicMobs can't be damage by players in a guild.

## Steps to Reproduce

1. Install MythicMobs & Guilds
2. Create a guild
3. Spawn a MythicMob
4. Attack it

## Your Environment

* Guilds version: ???
* MC Version: ???
* Plugin List: MythicMobs

**Comment by wolfebersahd** [comment]
I have MythicMobs on my server, I will test this thoroughly when I get home.

**Comment by wolfebersahd** [comment]
Works fine on:
**Paper 1.12.2
MythicMobs 4.3.2
Guilds 3.5.3.7**

**Comment by wolfebersahd** [comment]
Tested with...
![Capture1](https://user-images.githubusercontent.com/9948243/68549087-53a3bd80-03c2-11ea-8655-afc52b4c7815.PNG)
![Capture2](https://user-images.githubusercontent.com/9948243/68549089-556d8100-03c2-11ea-97a8-099e91d82912.PNG)
And still can't reproduce it.

**Comment by darbyjack** [comment]
Closing as I wasn't able to reproduce either.
