### ISSUE TITLE
Players can add items to the `/guild members` list.

### ISSUE THREAD

**Issue by wolfebersahd** [guilds-plugin/Guilds#268]
## Description
Player can click, drag and drop item into the `/guild members` gui. if the gui is closed the item is lost.

## Expected Behavior
The /`guild members` GUI should behave the the `/guild list` GUI and prevent players from dropping items into the GUI.

## Actual Behavior
Player can pick up, drag, and drop items into the `/guild members` gui.

## Possible Fix
`/guild members` gui should function like `/guild list` gui.

## Steps to Reproduce
1. Create a guild
2. Open the `/guild members` gui
3. Drag items into the `/guild members` gui

## Context
Players can lose items because of this.

## Your Environment
* Guilds version: 3.5.3.8 BETA
* MC Version: Paper 1.12.2
* Plugin List: I'd rather not say.

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/commit/d441eee4f62c36da7bc89051b85ee7abcc54a2c2
