### ISSUE TITLE
Request to change buff perm

### ISSUE THREAD

**Issue by troes1** [guilds-plugin/Guilds#278]
Currently de buff perms are based on the type of the buff but it would be more useful if it was based on the name. I want to have multiple buffs with the same type but with different durations/amplifiers each with a unique perm.

If you have any questions let me know.

**Comment by DeniedINC** [comment]
I may be mistaken but I was under the impression that you can make custom buffs and the permission goes off of the name. So making haste2: as the name for example would have a permission guilds.buff.haste2

I would test that out see what happens

**Comment by wolfebersahd** [comment]
Currently only the 9 buffs are possible with varying degrees of editing.

There are plans to redo the whole buff system, not sure when that'll be done, but essentially you will be able to create multiple buffs of various level, even buffs that combine multiple buffs into a single buff. I saw the concept behind the feature and it's going to be sick. Just need to wait for Glare to have enough free time to do it 😉

**Comment by troes1** [comment]
This has been added in version 3.5.4.5
