### ISSUE TITLE
Tier Cost Request

### ISSUE THREAD

**Issue by DeniedINC** [guilds-plugin/Guilds#280]
I am interested in adding a different type of cost for guild upgrades. I would want players to be able to upgrade guilds using items, preferably support with MMOItems and QuantumRPG.

New way to upgrade guilds especially for RPG like servers such as the one I've been working on.

I am personally going to be having guild wars and if this feature is implemented giving guilds special items for winning which can allow them to upgrade their guild. Also with custom professions and materials found in the world and from bosses that guilds have to come together to farm and defeat. I think this would be an amazing addition and hopefully won't a pain to code XD

Possible Implementation
Search a guilds vault for items to upgrade and if they have them remove the item and upgrade the guild.

**Comment by wolfebersahd** [comment]
You can already accomplish this with a third party plugin like DeluxMenus that will handle the cost of any required 3rd party items.

 - Use a permission plugin to block guild upgrade
 - Set the cost-to-upgrade in the config 0
 - Use DeluxMenus to create an upgrade GUI with the relevant costs
 - Have DeluxMenus execute the guild upgrade command with OP perms after removing the require items from the player.

That should handle what you're expecting.

(ADDING THIS HERE JUST FOR EASE OF FINDING IT)

**Comment by darbyjack** [comment]
As stated above, this can already be done via 3rd-party plugins, I don't plan to add this in since it's pretty easy to do via a plugin such as DeluxeMenus.
