### ISSUE TITLE
Current buff placeholder

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#283]
## Context
Current guild buff placeholder return current buff name.
But I don’t know how to better display stacked buffs. They can be separated by a comma, but even in this case the line can be long if somewhere other than chat (scoreboard, menu item)

You can display the current buff in a convenient place.

**Comment by darbyjack** [comment]
This should be possible now via a plugin that wants to hook into Guilds. There's now an event that fires when a buff is purchased for a Guild!
