### ISSUE TITLE
Guild player join error

### ISSUE THREAD

**Issue by HunterJackson765** [guilds-plugin/Guilds#284]
URL for the error - https://pastebin.com/U1mdBg1r

Problem - Whenever someone joins the server and they are in a Guild this error comes up

MC Version - Paper 1.15.1
Guild Version - 3.5.4.1
Plugin that might be involved - PermissionsEx

**Comment by troes1** [comment]
Hey,

Have you set run-vault-async to false in the config file?

**Comment by darbyjack** [comment]
He didn't. Doesn't look like he read through the config.
