### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by kforbro** [guilds-plugin/Guilds#290]
Editing these lines doesn't change anything in the game

help:
  header: "<c3>=== </c3><c1>Showing help for </c1><c2>{commandprefix}{command}</c2><c3> ===</c3>"
  detailed-header: "<c3>=== </c3><c1>Showing detailed help for </c1><c2>{commandprefix}{command}</c2><c3> ===</c3>"
  format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
  command-format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
  parameter-format: "<c2>{syntaxorname}</c2>: <c3>{description}</c3>"
  page-info: "Showing page <c3>{page}</c2> of <c2>{totalpages}</c2> (<c3>{results}</c3> results)."
  search-header: "<c3>=== </c3><c1>Search results for </c1><c2>{commandprefix}{command} {search}</c2><c3> ===</c3>"

**Comment by darbyjack** [comment]
Make sure you're modifying the right language file!

**Comment by kforbro** [comment]
I checked everything thoroughly.

**Comment by kforbro** [comment]
https://imgur.com/a/H1ZZw6J

**Comment by kforbro** [comment]
https://imgur.com/a/qD3dUsy
Even that doesn't work

**Comment by kforbro** [comment]
https://i.imgur.com/XGjxJ4A.png

**Comment by kforbro** [comment]
It turned out that you can only configure help localization in the acf-core_**file.properties, which is very inconvenient https://imgur.com/a/NQ6Ac1s

**Comment by darbyjack** [comment]
Sorry for the frustration. I'm planning on overhauling the language system in the near future to make sure everything you would need would be in them.

**Comment by kforbro** [comment]
Previously, these lines could be changed in acf-core_**. properties, but now they are not in .jar. What should I do?
https://i.imgur.com/1ppo1WO.png
https://i.imgur.com/Udb2RcK.png

**Comment by darbyjack** [comment]
What exactly are you trying to change now? In the next major update after the one releasing shortly, I'm planning to overhaul the language system to ensure that all messages can be accessed from the language files instead of some leftover from the command library that the project utilizes.

**Comment by darbyjack** [comment]
Closing due to inactive response form the requester. Feel free to re-open if this is still an issue.
