### ISSUE TITLE
Language file：zh-tw 繁體中文

### ISSUE THREAD

**Issue by david890504** [guilds-plugin/Guilds#296]
---
descriptions:
  accept: "同意公會邀請"
  admin-addplayer: "以管理員身份強制將玩家添加到公會"
  admin-bank-balance: "以管理員身份查看公會財產"
  admin-bank-deposit: "以管理員身份為公會銀行增加錢款"
  admin-bank-withdraw: "以管理員身份從公會銀行拿出錢款"
  admin-claim: "以管理員身份為公會占地"
  admin-delhome: "以管理員身份刪除公會領地"
  admin-home: "以管理員身份傳送至公會領地"
  admin-motd: "以管理員身份查看公會的圖標"
  admin-motd-set: "以管理員身份設置公會的圖標"
  admin-motd-remove: "以管理員身份移除公會的圖標"
  admin-prefix: "以管理員身份強制更改公會前綴"
  admin-rename: "以管理員身份強制重命名公會"
  admin-remove: "以管理員身份強制從伺服器中刪除公會"
  admin-removeplayer: "以管理員身份強制從公會中刪除玩家"
  admin-sethome: "以管理員身份設置公會的領地"
  admin-status: "以管理員身份強制更改公會狀態"
  admin-spy: "以管理員身份強制監控公會聊天"
  admin-transfer: "以管理員權限將一個公會轉讓給另一個人"
  admin-unclaim: "以管理員身份取消公會占地"
  admin-upgrade: "以管理員身份強制升級公會等級"
  admin-vault: "以管理員身份強制查看公會倉庫"
  ally-accept: "接受來自另一個公會的結盟邀請"
  ally-add: "添加與自己公會結盟的盟友"
  ally-decline: "拒絕來自另一個公會的結盟邀請"
  ally-list: "列出盟友公會列表"
  ally-remove: "將一個公會從盟友公會中移除"
  arena-challenger: "設置競技場中挑戰者的位置"
  arena-create: "創建一個戰爭競技場"
  arena-defender: "設置競技場中防禦者的位置"
  arena-delete: "刪除一個戰爭競技場"
  arena-list: "列出所有已創建的競技場"
  arena-tp: "傳送至一個競技場"
  bank-balance: "顯示公會銀行餘額"
  bank-deposit: "將金幣存入公會銀行"
  bank-withdraw: "將金幣從公會銀行取出"
  buff: "打開公會增益效果界面"
  cancel: "取消"
  chat: "切換至公會聊天頻道"
  check: "查看待處理的公會邀請"
  claim: "設置當前位置為公會領地"
  code-create: "為你的公會創建一個邀請碼"
  code-delete: "刪除公會中的邀請碼"
  code-info: "查看邀請碼的信息"
  code-list: "列出公會中的所有邀請碼"
  code-redeem: "使用邀請碼加入公會"
  confirm: "確認"
  console-backup: "備份此插件的數據"
  console-migrate: "遷移存儲數據"
  console-unclaim-all: "以管理員身份取消全服所有公會的領地"
  console-update-languages: "用於更新語言文件的控制臺指令"
  create: "創建公會"
  decline: "拒絕公會邀請"
  delete: "刪除公會"
  delhome: "取消公會領地傳送點"
  demote: "降級公會成員位階"
  give: "給予玩家公會升級券"
  help: "開啟幫助列表"
  home: "前往公會領地傳送點"
  info: "打開公會詳細信息界面"
  invite: "請一名玩家加入你的公會"
  kick: "將一個玩家從你的公會踢出"
  language: "更改你的語言預設文件"
  leave: "離開你的公會"
  list: "列出所有公會"
  members: "打開公會成員列表"
  motd: "查看你公會的圖標"
  motd-set: "設置你公會的圖標"
  motd-remove: "移除你公會的圖標"
  prefix: "更改你的公會前綴"
  promote: "升級公會成員位階"
  reload: "chongzia"
  rename: "更改你的公會名"
  request: "申請加入公會"
  sethome: "設置你的公會領地"
  status: "更改你的公會狀態"
  transfer: "將你的公會轉移給其他玩家"
  unclaim: "取消你的公會領地"
  upgrade: "提升公會等級"
  vault: "打開公會倉庫"
  version: "查看插件信息"
  war-accept: "接受一個戰爭競技"
  war-challenge: "發起與另一個公會的戰爭"
  war-deny: "拒絕一個戰爭競技"
  war-join: "加入一個等待中的戰爭"
create:
  guild-name-taken: "&7[&6公會&7]&f此公會名已有人使用!"
  warning: "&7[&6公會&7]&f創建公會將會花費{amount}金幣 輸入/g confirm來確認創建 如果取消創建請輸入/g cancel"
  successful: "&7[&6公會&7]&f公會{guild}&f創建成功"
  cancelled: "&7[&6公會&7]&f已取消創建公會"
  requirements: "&7[&6公會&7]&f非法的公會名稱，請重新嘗試并限制公會名在64字以內"
  name-too-long: "&7[&6公會&7]&f你沒有設置公會前綴,請嘗試輸入更短的名稱或創建時輸入公會前綴"
  prefix-too-long: "&c公會前綴不滿足要求! 可能是輸入了過多字符?"
chat:
  disabled: "&7[&6公會&7]&f已關閉公會聊天頻道"
  enabled: "&7[&6公會&7]&f已開啟公會聊天頻道"
request:
  success: "&7[&6公會&7]&f對公會[{guild}&f]的申請已發出，請等待處理"
  incoming-request: "&7[&6公會&7]&f{player}請求加入公會,請輸入/g invite {player} 來確認"
  cooldown: "&7[&6公會&7]&f你在{time}內無法發送任何請求"
error:
  already-in-guild: "&7[&6公會&7]&f你已擁有一個公會!"
  no-guild: "&7[&6公會&7]&f你沒有加入公會!"
  role-no-permission: "&7[&6公會&7]&f你沒有足夠的權限這麼做!"
  tier-no-permission: "&c你的公會等級不夠高!"
  guild-no-exist: "&7[&6公會&7]&f該公會不存在（如果你想加入的公會含有自定義顏色，請嘗試與公會管理員溝通邀請你加入）"
  player-not-found: "&7[&6公會&7]&f玩家 {player} &f不在線"
  player-not-in-guild: "&7[&6公會&7]&f玩家{player} 不在你的公會中"
  not-officer: "&7[&6公會&7]&f只有副會長以上的位階才能使用"
  blacklist: "&7[&6公會&7]&f你的公會名稱/公會前綴有不雅文字，請重新規範你的操作"
  not-enough-money: "&7[&6公會&7]&f你沒有足夠的錢這麼做"
  economy-required: "&7[&6公會&7]&f伺服器未安裝經濟插件,請聯系管理員"
  buff-cooldown: "&7[&6公會&7]&f抱歉,你的公會在近期已購買了一個BUFF,請等待{amount}秒後重試"
  buff-no-permission: "&c抱歉, 你沒有權限購買這個增益效果!"
  no-pending-invites: "&c抱歉, 你沒有待接受的公會邀請!"
  migrating: "&7[&6公會&7]&f抱歉,暫時無法執行該操作,數據遷移中請稍後再試"
  console-command: "&7[&6公會&7]&f該操作只允許後臺執行"
  transfer-same-person: "&7[&6公會&7]&f你無法將公會轉讓給已是該公會的會長的人"
  player-no-exist: "&7[&6公會&7]&f未在伺服器上找到該玩家"
bank:
  balance: "&7[&6公會&7]&f當前公會銀行: {amount}金幣"
  deposit-success: "&a{player} 存入了 {amount} 至公會銀行. 現在的餘額為 {total}."
  withdrawal-success: "&a{player} 從公會銀行拿取了 {amount}. 現在的餘額為 {total}."
  not-enough-bank: "&7[&6公會&7]&f銀行裡沒有足夠的金幣"
  over-max: "&7[&6公會&7]&f你不能存入這麼多的金幣，已超出容量"
admin:
  delete-warning: "&7[&6公會&7]&f你正要刪除 {guild}，輸入 /g confirm 來確認或輸入 /g cancel 來取消"
  delete-success: "&7[&6公會&7]&f你已成功的移除 {guild}"
  guild-vault-sign: "&7[&6公會&7]&f全球公會銀行已創建!"
  player-added: "&7[&6公會&7]&f你已被管理員加入至 {guild} ！"
  admin-player-added: "&7[&6公會&7]&f你已添加玩家 {player} 至 {guild}公會!"
  admin-guild-add: "&7[&6公會&7]&f{player} 已被管理員強制加入至你的公會!"
  player-removed: "&7[&6公會&7]&f你已被管理員從 {guild} 移除!"
  admin-player-removed: "&7[&6公會&7]&f你已從 {guild} 移除玩家 {player} ！"
  admin-guild-remove: "&7[&6公會&7]&f{player} 已被管理員強制移除自你的公會!"
  admin-upgrade: "&7[&6公會&7]&f你已成功升級 {guild}至下一個等級!"
  admin-guild-upgrade: "&7[&6公會&7]&f你的公會階級已由管理員升級!"
  spy-on: "&7[&6公會&7]&f開啟監視公會聊天頻道!"
  spy-off: "&7[&6公會&7]&f關閉監視公會聊天頻道!"
  motd: "&a{guild} 的圖標為: {motd}"
  motd-success: "&7[&6公會&7]&f你成功為公會{guild}設置了圖標為{motd}"
  motd-remove: "&7[&6公會&7]&f你已成功為公會{guild}移除了圖標"
  bank-balance: "&a{guild} 的銀行餘額為 {balance}."
  bank-deposit: "&a成功地為 {guild} 的銀行存入 {amount}. 新的餘額為 {total}."
  bank-withdraw: "&a成功地從{guild} 的銀行拿取 {amount}. 新的餘額為 {total}."
  sethome: "&a成功地為 {guild} 設置了領地."
  home: "&a成功地傳送至 {guild} 的領地."
  delhome: "&a成功地為 {guild} 移除了領地."
boot:
  player-kicked: "&7[&6公會&7]&f玩家 '{player}' 已被 {kicker} 踢出!"
  successful: "&7[&6公會&7]&f已踢出玩家 {player}"
  kicked: "&7[&6公會&7]&f你已被 {kicker} 踢出公會"
decline:
  success: "&7[&6公會&7]&f公會邀請遭到拒絕!"
demote:
  cant-demote: "&7[&6公會&7]&f無法降級該玩家位階!"
  demote-successful: "&7[&6公會&7]&f已調整玩家 {player}的公會位階 [{old}] — [{new}]"
  you-were-demoted: "&7[&6公會&7]&f你的公會位階已被調整 [{old}] — [{new}]"
promote:
  cant-promote: "&7[&6公會&7]&f無法升級該玩家位階!"
  promote-successful: "&7[&6公會&7]&f已調整玩家 {player}的公會位階 [{old}] — [{new}]"
  you-were-promoted: "&7[&6公會&7]&f你的公會位階已被調整 [{old}] — [{new}]"
delete:
  successful: "&7[&6公會&7]&f成功刪除公會 {guild}"
  cancelled: "&7[&6公會&7]&f已取消操作"
  warning: "&7[&6公會&7]&f輸入/g confirm 來刪除公會 輸入/g cancel取消操作"
  notify-allies: "&7[&6公會&7]&f公會{guild}已不再是你的盟友,該公會已被刪除"
leave:
  cancelled: "&7[&6公會&7]&f已取消操作"
  successful: "&7[&6公會&7]&f你已離開公會"
  player-left: "&7[&6公會&7]&f玩家 {player} 退出了公會"
  guildmaster-left: "&7[&6公會&7]&f非常遺憾,你的公會會長 {player} 已解散公會"
  warning: "&7[&6公會&7]&f輸入 /g confirm離開公會 輸入 /g cancel取消"
  warning-guildmaster: "&7[&6公會&7]&f警告！你為公會會長，若你離開公會,公會將被解散，且此操作無法撤回，輸入/g confirm 解散公會 輸入/g cancel取消"
transfer:
  newmaster: "&7[&6公會&7]&f前任會長已轉讓會長至你的名下,你已成為當前公會會長"
  success: "&7[&6公會&7]&f已轉讓公會!"
invite:
  already-invited: "&7[&6公會&7]&f已邀請玩家至你的公會"
  message: "&7[&6公會&7]&f {player} 邀情你加入他的公會 {guild} .輸入 /g join {guild} 即可加入!"
  successful: "&7[&6公會&7]&f已成功邀請玩家 {player} 加入你的公會!"
  already-in-guild: "&c{player} 已經在另一個公會之中!"
upgrade:
  tier-max: "&7[&6公會&7]&f公會已達最高等級"
  money-warning: "&7[&6公會&7]&f你將會消耗 {amount} 金幣以升級你的公會[輸入/g confirm 繼續]"
  cancel: "&7[&6公會&7]&f已取消"
  success: "&7[&6公會&7]&f你已成功升級你的公會"
  not-enough-money: "&7[&6公會&7]&f你沒有足夠的金幣來升級公會，你還需要 {needed} 金幣!"
  not-enough-members: "&7[&6公會&7]&f你需要至少 {amount} 位公會成員來升級公會"
prefix:
  successful: "&7[&6公會&7]&f已成功更改公會前綴成 {prefix}!"
  disabled: "&7[&6公會&7]&f當前已禁用前綴功能"
status:
  successful: "&7[&6公會&7]&f公會狀態已更新為 {status}!"
rename:
  successful: "&7[&6公會&7]&f公會名稱已更改為 {name}!"
home:
  no-home-set: "&7[&6公會&7]&f找不到公會領地傳送點! 請使用/g sethome 來設定!"
  teleported: "&7[&6公會&7]&f你已傳送至公會領地!"
  cooldown: "&7[&6公會&7]&f你必須等待{amount}秒後才能執行此操作"
  warmup: "&7[&6公會&7]&f即將在 {amount} 秒後傳送. 請勿移動!"
  cancelled: "&7[&6公會&7]&f已取消傳送!"
sethome:
  successful: "&7[&6公會&7]&f你已設置公會領地傳送點!"
  deleted: "&7[&6公會&7]&f你已成功刪除你的公會領地!"
  cooldown: "&7[&6公會&7]&f你必須等待{amount}秒後才能執行此操作"
reload:
  reloaded: "&7[&6公會&7]&f已重載"
cancel:
  error: "&7[&6公會&7]&f你沒有需要取消的操作!"
  success: "&7[&6公會&7]&f已取消此操作!"
confirm:
  error: "&7[&6公會&7]&f你沒有要確認的操作!"
  success: "&7[&6公會&7]&f已確認操作!"
ally:
  none: "&7[&6公會&7]&f你沒有任何的盟友!"
  list: "&7[&6公會&7]&f你的公會與以下公會結盟: {ally-list}"
  current-declined: "&7[&6公會&7]&f{guild}的結盟請求已拒絕!"
  target-declined: "&7[&6公會&7]&f你與 {guild} 的結盟申請已被拒絕!"
  current-accepted: "&7[&6公會&7]&f你已同意與 {guild} 的結盟邀請"
  target-accepted: "&7[&6公會&7]&f你請求與 {guild} 的結盟請求已被同意"
  invite-sent: "&7[&6公會&7]&f你已發送邀請給 {guild}"
  incoming-invite: "&7[&6公會&7]&f你有來自 {guild} 的結盟邀請"
  current-remove: "&7[&6公會&7]&f你已移除 {guild} 從結盟名單！"
  target-remove: "&7[&6公會&7]&f{guild} 已取消與你的結盟!"
  already-ally: "&7[&6公會&7]&f此公會已與你結盟!"
  same-guild: "&7[&6公會&7]&f你無法邀請你自己結盟!"
  not-allied: "&7[&6公會&7]&f未找到公會!"
  already-requested: "&7[&6公會&7]&f你目前已有一個關於該公會的結盟請求!"
accept:
  not-invited: "&7[&6公會&7]&f該公會無需申請即可進入"
  guild-full: "&7[&6公會&7]&f該公會人數已滿!"
  player-joined: "&7[&6公會&7]&f{player} 已加入公會!"
  successful: "&7[&6公會&7]&f你已加入公會 {guild}"
  cooldown: "&7[&6公會&7]&f你目前正在加入公會冷卻期,請等待{amount}後重試"
claim:
  already-exists: "&7[&6公會&7]&f你已設置了公會領地,請嘗試刪除之前的領地後重試\""
  overlap: "&7[&6公會&7]&f距離其他公會的領地太近了,請嘗試換到其他的位置"
  success: "&7[&6公會&7]&f已設立公會領地! [{loc1} - {loc2}]"
  hook-disabled: "&7[&6公會&7]&f請在配置中開啟領地設置"
  sign-not-enabled: "&c這個功能沒有被開啟, 請在配置文件中打開這個設置!"
  sign-no-permission: "&c你沒有權限創建占地告示牌!"
  sign-invalid-format: "&c無效占地告示牌格式, 請重試!"
  sign-invalid-region: "&c無效 Worldguard 區域!"
  sign-placed: "&a成功地為 {region} 創建了占地告示牌. 價格為 {price}."
  sign-not-enough: "&c你的公會銀行沒有足夠的錢支付公會占地."
  sign-forced: "&c你只能通過占地告示牌來占地! 咨詢你的伺服器管理者以尋求幫助!"
  sign-buy-success: "&7[&6公會&7]&f你購買了這個區域"
unclaim:
  success: "&7[&6公會&7]&f你已成功刪除你的公會領地!"
  not-found: "&7[&6公會&7]&f公會領地不存在!"
  all-warning: "&7[&6公會&7]&f重要操作!你確定要刪除全服所有公會的領地數據嗎?是請輸入/g confirm否則請輸入/g cancel取消"
  all-cancelled: "&7[&6公會&7]&f已刪除伺服器所有公會的領地設置"
  all-success: "&7[&6公會&7]&f已成功刪除伺服器上所有的領地信息"
pending:
  invites: "&7[&6公會&7]&f你有來自公會的 {number} 個待處理邀請:  {guilds}   使用 /g accept <name> 或 /g deny <name> 來處理請求!"
codes:
  created: "&7[&6公會&7]&f你創建了新的邀請碼: {code} X {amount} 請及時使用!"
  empty: "&7[&6公會&7]&f你沒有邀請碼了,請重新創建!"
  list-header: "&7[&6公會&7]&f以下是公會當前的邀請碼:"
  list-item: "&7[&6公會&7]&fID: {code} | 剩餘數量: {amount} | 創建者: &6{creator}"
  deleted: "&7[&6公會&7]&f已移除該邀請碼!"
  invalid-code: "&7[&6公會&7]&f該邀請碼不存在,請重試"
  joined: "&7[&6公會&7]&f你使用了邀請碼加入了公會 {guild}"
  guild-message: "&7[&6公會&7]&f玩家{player}使用了{creator}的邀請碼加入了公會"
  out: "&7[&6公會&7]&f邀請碼已失效,請重試！"
  info: "&7[&6公會&7]&f邀請碼信息:\\n&fID: &6{code}\\n&a已使用: &6{amount}\\n&a創建者: &6{creator}\\n&6使用者: &6{redeemers}"
  max: "7[&6公會&7]&f你公會中的邀請碼已達上限"
vaults:
  maxed: "&7[&6公會&7]&f你不能打開公會倉庫 因為你已擁有當前公會等級的最大倉庫數量"
  blacklisted: "&7[&6公會&7]&f你不能把該物品放入公會倉庫,它已被列為黑名單物品"
languages:
  set: "&7[&6公會&7]&f你已設置語言文件為 {language}"
  warning: "&7[&6公會&7]&f該操作將更新所有語言文件， 這將刪除所有當前語言文件并重新創建, 輸入/guilds confirm 確認刪除，輸入/guilds cancel取消"
  updated: "&7[&6公會&7]&f已重新創建并重新加載語言文件"
backup:
  started: "&a正在備份所有Guilds數據!"
  finished: "&a所有的Guilds數據已經備份成功並且放入插件文件夾中了."
  warning: "&a你即將備份此插件的所有數據. 請確保沒有其他會消耗大量運算的工作. 輸入 /guilds confirm 繼續或輸入 /guilds cancel 取消."
  cancelled: "a你已取消此次備份."
help:
  header: "<c3>===</c3>顯示幫助</c1><c2>{commandprefix}{command}</c2><c3>===</c3>"
  detailed-header: "<c3>=== </c3><c1>顯示幫助詳細</c1><c2>{commandprefix}{command}</c2><c3> ===</c3>"
  format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
  command-format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
  parameter-format: "<c2>{syntaxorname}</c2>: <c3>{description}</c3>"
  page-info: "幫助頁<c2>{page}</c2>的 <c2>{totalpages}</c2> (<c3>{results}</c3>結果)."
  search-header: "<c3>=== </c3><c1>搜索幫助</c1><c2>{commandprefix}{command} {search}</c2><c3> ===</c3>"
motd:
  success: "&7[&6公會&7]&f你成功設置公會圖標為{motd}"
  remove: "&7[&6公會&7]&f你已成功移除公會的圖標"
  motd: "&7[&6公會圖標&7]&f {motd}"
  not-set: "&7[&6公會&7]&f你的公會還沒有設置圖標"
arena:
  created: "&a成功地創建名為 &c{arena} 的競技場&a! 請不要忘記設置重生點! 輸入 /g arena 查看更多"
  deleted: "&a成功地刪除名為 &c{arena} 的競技場&a"
  no-exist: "&c此競技場不存在."
  challenger-set: "&a成功地設置當前位置為 &c{arena}&a 的挑戰者位置!"
  defender-set: "&a成功地設置當前位置為 &c{arena}&a 的防禦者位置!"
  list: "&a伺服器上的競技場有: &c{arenas}&a."
  list-empty: "&c當前伺服器上還沒有創建好的競技場."
  position-not-set: "&c此隊伍的位置還沒有被設置. 請在傳送前先設置好次隊伍的位置!"
  teleported-to-selection: "&a成功地傳送至 &c{arena}&a 中 &c{team}&a 的出生點."
  all-full: "&c抱歉, 伺服器上所有的競技場都在使用中! 請稍後再試!"
war:
  no-defenders: "&c對面的弱雞公會人不夠, 無法接受挑戰."
  challenge-sent: "&a挑戰書已發送至 &b{guild}&a! 他們有&b{amount}&a秒來接受此次挑戰!"
  incoming-challenge: "&a注意! &b{guild} &a公會發來了一封挑戰書! &6輸入/g war accept接受公會戰&a或&6輸入/g war deny拒絕. &a你有&b{amount}&a秒來決定!"
  no-pending-challenge: "&c抱歉, 暫時沒有待處理的挑戰."
  already-challenging: "&c抱歉, 已經有一個挑戰在處理中. 請先取消它或等待它超時."
  no-self-challenge: "&cmdzz, 你想自己打自己?"
  guild-expired-challenge: "&c你對 &b{guild} &a發起的挑戰已經超時因為他們沒有及時接受."
  target-expired-challenge: "&c你的弱雞對手害怕得不敢及時接受. 挑戰被取消."
  challenge-denied-defender: "&a我理解, 戰爭不是對每個人都有利. 你拒絕了來自 &b{guild} &a的挑戰."
  challenge-denied-challenger: "&a你們對於 &b{guild} &a來說可能太過強大, 他們選擇不在這素晴日跟你們打架."
  not-enough-on: "&c你或者他們的公會沒有足夠的在線玩家來展開一場決戰."
  challenger-war-accepted: "&a準備好, &b{guild} &a接受了你們的公會挑戰! 加油加油! 你有 &b{amount} &a秒來輸入&b/g war join &a加入戰爭."
  defender-war-accepted: "&a準備好, 你接受了來自 &b{guild} &a的公會挑戰! 加油加油! 你有 &b{amount} &a秒來輸入&b/g war join &a加入戰爭."
  action-bar-join: "&a還有&b{amount}&a秒來加入戰爭. /g war join!"
  not-joinable: "&c抱歉, 此戰爭已經無法再加入了."
  not-enough-joined: "&c你或者他們的公會沒有足夠的玩家加入. 戰爭取消."
  already-at-max: "&c抱歉, 你們公會已經有足夠的玩家參加戰爭了!"
  war-joined: "&b{player} &a加入了公會戰爭!"
  action-bar-ready: "還有&b{amount}&a秒開始戰爭! 準備好!"
  winner: "&a炮火轟鳴，硝煙彌漫，遮云蔽日，慘不忍睹, 最終, &b{guild} &a的勇士們贏得了這場戰爭!"
  already-accepted: "&c你已經接受過了這場戰爭! 耐心點!"
  removed-for-size: "&a下列玩家被移除出戰爭以維持兩邊的平衡: {players}"
  defend-cooldown: "&b{guild} &c最近已經防禦過一次挑戰了. 讓他們休息一下以重整旗鼓吧!"
  commands-blocked: "&c抱歉, 戰爭中無法執行此命令!"
  player-killed-player: "&b{player} &a被 &b{killer}&a擊殺!"
  player-killed-other: "&b{player} &a被未知原因擊殺."
  player-killed-quit: "&b{player} &因為離開伺服器而被擊殺."
  teleported-back: "&a你打得太厲害了! 哎呀， 不是所有人都能做得這麼好. 你已被轉送到原來的位置!"
acf-core:
  invalid_syntax: "Usage: <c2>{command}</c2> <c3>{syntax}</c3>"
  permission_denied: "I'm sorry, but you do not have permission to perform this command."
  unknown_command: "Unknown Command, please type <c2>/help</c2>"
  error_performing_command: "I'm sorry, but there was an error performing this command."
migrate:
  invalid-backend: "&cThe backend you've attempted to migrate to is invalid."
  connection-failed: "&cConnecting to the new backend failed! Make sure your authentication is properly configured!"
  same-backend: "&cYou can't migrate to the same backend you are already using!"
  complete: "&aMigration of data ({amount} guilds) has been completed and will continue to use this new backend until being rebooted. Make sure to change your backend in the config to what you migrated to before you reboot!"
  warning: "&bImportant! &cYou are about to migrate ALL your plugin data. It is HIGHLY suggested that you make a backup of ALL data before doing this. If you lose your data, it can NOT be recovered. Are you sure you would like to continue? Type /guilds confirm to continue or /guilds cancel to cancel!"
  cancelled: "&aYou've successfully cancelled the migration of data!"

**Comment by darbyjack** [comment]
Please use https://crowdin.com/project/guilds
