### ISSUE TITLE
Error console 

### ISSUE THREAD

**Issue by istarengwa** [guilds-plugin/Guilds#300]
Hello =)

## Description
Each time a player who is a guild leader or guild member connects, a huge error message appears in the console, it's nothing with 3 players, but more and more people join guilds and that prevents me from working correctly with my console

connection of the founder op who is master of a guild : https://pastebin.com/DHQunhg1

guild master player login : https://pastebin.com/CQgxz6qd

guild member login : https://pastebin.com/2G8whpB7

op administrator without being in a guild : https://pastebin.com/TPF9Bqrx

## Possible Fix
It would just be necessary that the error is no longer displayed on the console if possible, or an option in the configuration to disable this, because players do not encounter any problem in game

## Steps to Reproduce
1. The message appears when connecting and logging out of each player in a guild, I'm not talking about a zone, but a guild. And this error also appears for OP people only present in guilds.

## Your Environment

* Guilds version 3.5.4.2
* MC Version 1.15.2
* Plugin List : Bank, BattlePass, Bitcoin, Citizens, ClearLag, CMI, CommandHook, Core, CoreProtect, CraftingStore, CrazyCrates, CustomEnderChest, DeadSouls, DiscordSRV, DragonEggDrop, EasterEggs*, ElytraBooster, ExpVip*, GravityTubes, Guilds, IALibs, Island, Jobs, MarriageMaster, mcMMO, mcMMOHorse, MineTinker, MiniaturePets*, MMOCore, MMOItems, MMOLib, MorphRedeem, Multiverse-Core, OldCombatMechanics, PermissionsEx*, PhysicsToGo, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, Quests, Seasons, Sentinel, ServerMarket, ServerRestart, SimpleEgg, SkinsRestorer, SkQuery, Skript, SuperLuckyBlock, Vault, VoidGenerator, VoidSpawn, WorldBorder, WorldEdit, WorldGuard

**Comment by darbyjack** [comment]
Your error is due to using PEx while having vault async to true. Change it to false in the config.
