### ISSUE TITLE
Bank withdraw not working

### ISSUE THREAD

**Issue by troes1** [guilds-plugin/Guilds#301]
## Description
When players withdraw money from their guild bank account it doesn't add it to their personal balance. I reproduced it with only vault and essentials running besides guilds. In that case instead of doing nothing it will even withdraw the money from your balance instead of adding.

## Steps to Reproduce
1. Add money to your account
2. Add money to your guild bank and check your balance and the guild balance
3. Withdraw money from guild bank
4. Check your balance

## Your Environment
* Guilds version: 3.5.4.3
* Minecraft version: 1.15.2
* Guilds3.5.4.3, Vault1.7.2, Essentialsx2.17.2.0

**Comment by wolfebersahd** [comment]
![guild withdrawal](https://user-images.githubusercontent.com/9948243/77936603-1d87ad00-7281-11ea-8c2f-d3e4db73da4b.PNG)

Withdrawing money from the bank also withdraws from user...

**Comment by darbyjack** [comment]
Fixed for the next update!
