### ISSUE TITLE
Player can't be kicked (or promoted)

### ISSUE THREAD

**Issue by troes1** [guilds-plugin/Guilds#302]
## Description
When a player changes his name and doesn't login after, the guild leader can't kick him. Also when he tries to promote the player. I get an error in the console. He also tried to kick the player by his new name but didn't work.

Here is the error message in the console: https://pastebin.com/TjGMb42d

## Steps to Reproduce
1. It is hard to reproduce. I didnt try to reproduce it (yet) but you can just add an acount to a guild. Leave the server and change the account name. Then try to kick that account. (Not sure if this would work)

## Your Environment
* Guilds version: Compiled from github with the latest changes
* MC Version 1.15.2 
* Plugin List: Would provide this if necessary

**Comment by darbyjack** [comment]
Yeah, it would look like it's failing to get the member based on the username that you input. I will have to try and think of a solution for this.
