### ISSUE TITLE
GuildLeaveEvent

### ISSUE THREAD

**Issue by troes1** [guilds-plugin/Guilds#308]
## Description
When I try to get the player when he gets kicked out of the guild with the GuildLeaveEvent I instead get the player who kicked the other player.

## Expected Behavior
Return the kicked player

## Actual Behavior
Returns the kicker

## Steps to Reproduce
1. Use the event when someone gets kicked and check the player it returns

## Your Environment
* Guilds version: Latest version
* MC Version: 1.15.2
* Plugin List: Would provide if needed

**Comment by darbyjack** [comment]
This has been addressed and handled in https://github.com/guilds-plugin/Guilds/pull/306. I have implemented a new GuildKickEvent and cleaned up the GuildLeaveEvent.
