### ISSUE TITLE
Guild buff cooldown

### ISSUE THREAD

**Issue by troes1** [guilds-plugin/Guilds#312]
## Description
I noticed that the buff cooldown has moved from the config.yml to the buff.yml. However in my case it's still using the cooldown that was set in the config file before it was removed. And It's not using the new cooldown from the buffs.yml file.

## Your Environment
* Guilds version: 3.5.4.5
* MC Version: 1.15.2
* Plugin List: Would provide if needed

**Comment by wolfebersahd** [comment]
Have you tried removing that line from the config.yml to force it to look at the buff.yml for the cooldown?

**Comment by troes1** [comment]
It automatically removed that line from the config.

**Comment by troes1** [comment]
I dont how and why but I changed it to 600 seconds and after a few restarts it grabbed the correct one.
