### ISSUE TITLE
Make PlaceholderAPI placeholders support.

### ISSUE THREAD

**Issue by MaxIsV** [guilds-plugin/Guilds#333]
## Context
 This change is important for me, because I love when the chat looks beautiful, for this in the sections "guild.format.chat" and "guild.format.spy" we need to add placeholder support from the PlaceholderAPI plugin.

I will customize the chat so that it looks beautiful
 Other users will also be able to decorate their chat with wonderful placeholders!

## Possible Implementation
 /guild admin add-support papi

**Comment by darbyjack** [comment]
Implemented via https://github.com/guilds-plugin/Guilds/commit/3f91a22071f4776ad01081858f73d6b896ac561b
