### ISSUE TITLE
After restart server offline player command not working.

### ISSUE THREAD

**Issue by chocolatecraft** [guilds-plugin/Guilds#334]
After restart server offline player command not working.
/guild admin removeplayer not working offline player.
and /g boot offline player not work too.
Can you do this work ?
1.Create guild
2.join 2nd player
3.log out 2nd player
4.restart server
5.use admin command or boot kick not join 2nd player

**Comment by chocolatecraft** [comment]
https://i.ibb.co/k52FSNR/Screenshot-2.png

**Comment by darbyjack** [comment]
I think I was able to reproduce this. I will be able to investigate more next week! Have a safe weekend!

**Comment by darbyjack** [comment]
Upon further investigation, I have not fully be able to recreate this issue.
