### ISSUE TITLE
Messages on a scoreboard or chat instead of the action bar to avoid incompatibilities with Custom HUDS of the plugin Items Adder

### ISSUE THREAD

**Issue by alejandro0256** [guilds-plugin/Guilds#336]
## Context
It would be possible an option to show the messages that appears in the actionbar in the chat, subtitles, scoreboard or a bossbar?

My server uses the plugin Items Adder that use the action bar to make custom HUDs and when another plugin uses the action bar it doesn't look so well because it switch form the HUD to the messages and creates flicker effect and doesn't look good.

**Comment by darbyjack** [comment]
I can add this to my to-do list.

**Comment by darbyjack** [comment]
I believe this was implemented via https://github.com/guilds-plugin/Guilds/commit/2c5bbf408360ed1ce6732789f26e70d885edde55
