### ISSUE TITLE
War Events

### ISSUE THREAD

**Issue by HauserGrim** [guilds-plugin/Guilds#337]
## Context

I want to be able to prevent players from participating in the war under certain conditions (even if they are ready)
I also had ideas about betting on wars and a war rank system.
I think other users will have many ideas how use this.

## Possible Implementation

GuildWarChallengeEvent
GuildWarAcceptEvent
GuildWarDeclineEvent
GuildWarReadyEvent
GuildWarStartEvent
GuildWarEndEvent

I had ideas about methods, but they were too dumb.

**Comment by darbyjack** [comment]
Which of these events are you wanting to be cancel-able?

**Comment by HauserGrim** [comment]
I thought for a long time about the events, but I was not able to come up with what I would consider sufficient.
Below is a copy of the attempts. Maybe this will help somehow, but I do not have normal ideas.
(I use a translator, the meaning of some phrases may be lost)

`GuildWarChallengeEvent
  Cancellable
  getChallenger
  getDefender
GuildWarAcceptEvent
  getGuild
GuildWarDeclineEvent
  getGuild
GuildWarStartEvent
  Cancellable
  getChallenger
  getDefender
  getChallengers
  getDefenders
GuildWarEndEvent
  ...
GuildWarWinEvent
  getGuild
  getPlayers (winners)
GuildWarLoseEvent
  getGuild
  getPlayers (losers)

GuildWarPlayerReadyEvent
  Cancellable
  getPlayer
GuildWarPlayerStartEvent
  Cancellable
  getPlayer

Method inWar(Player) or Player.inWar()`

**Comment by darbyjack** [comment]
Started working on this. Why would you have a start event cancel-able if you can just cancel the challenge event?

**Comment by darbyjack** [comment]
Started a PR: https://github.com/guilds-plugin/Guilds/pull/343

**Comment by darbyjack** [comment]
I believe all of this was implemented via https://github.com/guilds-plugin/Guilds/commit/7277f7f1ebadb8cd311e22cb697d79266bb2330e
