### ISSUE TITLE
Balance Placeholders Not Formatted The Same

### ISSUE THREAD

**Issue by UltraFaceguy** [guilds-plugin/Guilds#340]
## Description
Format is off on the max balance and balance placeholders (as well is in /guild info)

## Expected Behavior
Aligned format of balance placeholders

## Actual Behavior
50000 balance displays as 50,000
50000 max balance displays as 50000.00

## Possible Fix
Apply the format for balance to max balance :)

## Steps to Reproduce
do /guild info

## Context
It made me sad

## Your Environment
Everything 100% up to date

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/commit/2b12d805eac52daf7c3f7c4bea7d6856a4a4fe08
