### ISSUE TITLE
Better Repo Description

### ISSUE THREAD

**Issue by MitchTalmadge** [guilds-plugin/Guilds#344]
Hi there,

I came across this repo from GitHub's explore page and it took me a while to figure out what kind of server this was for. Initially I thought maybe Discord because there was a Discord link at the top of the README. 

Eventually I discovered that it was a Spigot plugin, but that is never mentioned in the README or repo description. All it says is that it is for "servers." 

I think this project looks awesome and you would benefit by specifying in the README and in the repo's short description that this is a Minecraft Spigot plugin. I understand that most people probably find this repo from the plugin page or forums, but some like myself may come from other avenues and not realize the potential of your creation.

:)

**Comment by darbyjack** [comment]
Thanks for this suggestion! I'll definitely improve the README!
