### ISSUE TITLE
Option to prevent guilds transfer to non-members

### ISSUE THREAD

**Issue by deadfish12** [guilds-plugin/Guilds#347]
## Context

I have set the join cooldown for guilds to prevent players from earning extra benefits that exceeds the maximum players amount. However, some players found out they can bypass the cooldown by transferring the guild to players that are not the guild's members.

It can benefit other users that have also set join cooldown to prevent their players from using /guilds transfer to bypass the cooldown.

## Possible Implementation

This option can be added in the config.yml or maybe by separating the permission for /guilds transfer to guilds.command.transfer.members and guilds.command.transfer.others

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/commit/cafc2184c49adfaf5d9d78f4be2e8fb2c9117593 Looks like it was always a bug.
