### ISSUE TITLE
Disable friendly fire in the Arena

### ISSUE THREAD

**Issue by MaxIsV** [guilds-plugin/Guilds#353]
## Context

The fact is that players in the same guild often want to fight with each other, so I allowed friendly fire. But then players from the same guild can also atack each other in the war arena. I want you to add a config option that will prohibit attacking your allies in the arena.

This will allow players to fight in the same guild whenever they want, but will not allow attacking allies in the war. I think it would be very convenient.

**Comment by darbyjack** [comment]
The opposite of this was implemented in the latest update. You can disable FF in the config and then permission-base allow it to work.

Hope this helps. Feel free to re-open if you have more.
