### ISSUE TITLE
About Guid name

### ISSUE THREAD

**Issue by nicklly** [guilds-plugin/Guilds#390]
I input Chinese as the name of the guild,it tip create success,as written in the picture below
![QQ截图20201129194223](https://user-images.githubusercontent.com/17716585/100540895-3cf53080-327b-11eb-85b4-9e95b0a834d2.png)

then I restart my server, the guild name will be change... I don't know what wrong 
![QQ截图20201129194631](https://user-images.githubusercontent.com/17716585/100540951-9cebd700-327b-11eb-920d-183dd3baa809.png)

if u know... pls help me
 thank you!

**Comment by darbyjack** [comment]
Looks like it's using a symbol that the system doesn't know how to process. Ensure everything you're doing with files supports UTF-8.
