### ISSUE TITLE
guild war bug

### ISSUE THREAD

**Issue by xXDarkCvBxX** [guilds-plugin/Guilds#394]
## Description

When using the /guild war command, when accepting the war request it starts giving errors in the cmd, as if it was not able to replay the countdown to confirm the guild war
## Expected Behavior

It should work without any errors in the cmd.
## Actual Behavior

Give errors every second that passes the counter to start the guild war.
## Context

When trying to use / guild war accept, it seems that the countdown gives errors on the cmd.
## Your Environment

* Guilds version 3.5.5.3
* MC Version 1.16.4
* Plugin List - AdvancedEnchantments, Authme, BuyCraft, Citizens, Combatlogx, CrazyAuctions, CrazyCrates, dtlTraders, EntityTracker, EssentialsX, EssentialsXChat, EssentialXSpawn, GriefPrevention, Guilds, Holographic Displays, Jobs, LibDisguise, LimitPillager, LuckPerms, MyhticMobs, MithicArtifacts, NoCheatPlus, NuVotifier, OpenAudioMc, ProtocolLib, SAML, SkinRestorer, Staff+, Skript, Tablist, Vault, VillagerOptimiser, VotingPlugin, Wildtp, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by darbyjack** [comment]
This has been fixed and will be in the next update!
