### ISSUE TITLE
is have support 1.16.4???

### ISSUE THREAD

**Issue by zhengzhe46** [guilds-plugin/Guilds#395]
![unknown3](https://user-images.githubusercontent.com/55218211/102577912-f127ff80-4133-11eb-9a9a-6f25bc6c8912.png)
![unknown2](https://user-images.githubusercontent.com/55218211/102577915-f1c09600-4133-11eb-8c18-25d367cbb0b2.png)
![unknown](https://user-images.githubusercontent.com/55218211/102577917-f2592c80-4133-11eb-90eb-b50d53a1390e.png)

**Comment by darbyjack** [comment]
Yes! It works fine on 1.16.4, did you compile this yourself?

**Comment by zhengzhe46** [comment]
no，I know compile .I continued to try

**Comment by darbyjack** [comment]
Use `gradle ShadowJar` to compile properly.
