### ISSUE TITLE
Can't set 'Member' as name for roles.yml in certain ranks

### ISSUE THREAD

**Issue by blek-id** [guilds-plugin/Guilds#401]
## Description
Right now we can't set Member to be not the lowest rank. Something is defaulting the word 'member' to be the lower rank

## Expected Behavior
player rank will be on '4' (this example. recruit)

## Actual Behavior
player will have rank number '3' (member). when changing name of role '3' to Veteran or anything else, joining player will be on '4'.

## Steps to Reproduce
1. try and change role on '3' name to Member. (roles.yml provided in Context)
2. invite new player to guild

## Context
Can't set roles to be like this
roles.yml https://pastebin.com/UcKT6q6u

## Your Environment

* Guilds version -  3.5.5.6
* MC Version - 1.16.4
* Plugin List - I don't think this is relevant

**Comment by darbyjack** [comment]
Hi there,

Apologies on the late response to this. 

Is there any way to give more information on how to reproduce this? I took your file (pastebin.com/UcKT6q6u) and I made the change (setting 3 name to be Member). Then, I invited a player to the Guild, and they were given the Recruit role.

Thanks,
Glare.

**Comment by blek-id** [comment]
Will test out again in my side, close for now and I'll re-open if it's happening
