### ISSUE TITLE
Ally Chat command missing

### ISSUE THREAD

**Issue by blek-id** [guilds-plugin/Guilds#406]
## Description
Can't find any command for ally chat

## Expected Behavior
Should be a command named /guild chat ally or something similar so we can chat with allies

## Actual Behavior
No command like so.

## Your Environment

* Guilds version - Latest
* MC Version - 1.16.4
* Plugin List - Irrelevant

**Comment by VQ9** [comment]
I will see what I can do about it

**Comment by darbyjack** [comment]
Will be implemented when https://github.com/guilds-plugin/Guilds/tree/ally-chat is merged.

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/guilds-plugin/Guilds/commit/d678b3c298945f2f3a582a4e5d760d5df7bfc79a.
