### ISSUE TITLE
Convert data into mysql

### ISSUE THREAD

**Issue by hkkongou** [guilds-plugin/Guilds#446]
## Context

Would it be possible to convert guild data into mysql database? i have a server running almost a year and the files are not mysql, i am going to set up new server and i want to sync them, but i found out that guilds seems not support file format transfer from yml to database, which means that if i switch to mysql directly, all data will be loss : (

## Possible Implementation

make a converter to transfer yml data into mysql

**Comment by darbyjack** [comment]
There's a command in the plugin that does this. /Guild migrate
