### ISSUE TITLE
[bug] mysql does not sync (only upon server stop)

### ISSUE THREAD

**Issue by hkkongou** [guilds-plugin/Guilds#449]
## Description

i am planning to use mysql to sync all server guilds, i just converted some old guild data from yaml to mysql, however, during test between two server connected to same mysql, i found out that the data does not sync in game, according to the default mysql config in config.yml, it should sync each 1min, however, i have waited for 5-10mins, the data does not sync totally.

To test,i have made a guild in server a, and then i go server b, but server b say i don't have a guild, even tho i have waited for 5-10 mins. only when i restart server, both server say i have guild.

I have also tried to delete guild, but the behaviour looks random, depending on which server close last, the last server will wipe the other server data stored eariler?

## Expected Behavior

it should sync when a player is doing something, such as pull something out of guild chest or bank, otherwise if a player go to another server to open same guild bank, they can dupe things. 

## Actual Behavior

it does not sync unless the server close

## Possible Fix

detect every activity and sync the change to mysql instantly 

## Steps to Reproduce

1. connect two server using mysql
2. make a guild in server a
3. go to server b and wait
4. server b does not sync unless server close

## Context

player can dupe things, or it would be very inconvenient for them.

## Your Environment

* Guilds version 3.5.5.8
* MC Version 1.16.5 
* Plugin List
![image](https://user-images.githubusercontent.com/61608872/120166301-064ea180-c22f-11eb-9c6e-264c397d0216.png)

**Comment by darbyjack** [comment]
The way the plugin works is the data is loaded on startup and periodically saved to the database. It will not pull again from the database until the next reboot.
