### ISSUE TITLE
copy money

### ISSUE THREAD

**Issue by zz2423257** [guilds-plugin/Guilds#450]
## Description
Put enough money in the guild bank first
enter /g upgrade
Later, withdraw all the balance of the guild
Then enter /g confirm
The upgrade will be completed and the guild balance will be retained!

## Expected Behavior
So you can use this bug to copy money

## Actual Behavior
So you can use this bug to copy money

## Steps to Reproduce

1.Put enough money in the guild bank first
2.enter /g upgrade
3.Later, withdraw all the balance of the guild
4.Then enter /g confirm

## Your Environment

* Guilds version Guilds-3.5.5.8
* MC Version 1.16.15

**Comment by darbyjack** [comment]
Hey there, I have not been able to reproduce this via the steps you have provided. Any chance you can record a video of this for me to help me out?

**Comment by zz2423257** [comment]
[https://youtu.be/2zwb5aFKvD0](url)

**Comment by darbyjack** [comment]
I believe this was fixed via https://github.com/guilds-plugin/Guilds/commit/fabc51142bd9335e8ce5c32948b3464f82f2bc86
