### ISSUE TITLE
[Bug?] When Guilds is installed, the server is randomly shutdown

### ISSUE THREAD

**Issue by Yurinann** [guilds-plugin/Guilds#479]
Hi! When i installed this plugin on my server, it sometimes has a random shutdown problem. There isn't any notices in my server cmd. My English is bad sry

**Comment by darbyjack** [comment]
I would need logs to be able to help.

**Comment by Yurinann** [comment]
no logs.. There is no obvious regularity for restarting, but after I deleted this plug-in and observed repeatedly, there was no such situation

**Comment by Yurinann** [comment]
I'd be happy to provide you with more helpful information, but it's true that there wasn't any unusual log output at the time of this issue. Since this issue has been on hold and I've abandoned Guilds for a long time, I've decided to close this issue for now and bring it back when I have time to test it later.
