### ISSUE TITLE
guild admin transfer cause error

### ISSUE THREAD

**Issue by hkkongou** [guilds-plugin/Guilds#480]
## Description
when i try to transfer a guild owner to another user using /g admin transfer
it show
![image](https://user-images.githubusercontent.com/61608872/127012696-889c74ee-599c-4e78-bcc0-26a4830b979e.png)

## Expected Behavior
it should work

## Actual Behavior
it show error , alot of error message in console

https://paste.gg/p/anonymous/6bbdb0383393446796d347afbea020a2

## Possible Fix
idk

## Steps to Reproduce
1. type /guild admin transfer 
2. press tab, choose the first one

## Context

cannot use this function
https://paste.gg/p/anonymous/6bbdb0383393446796d347afbea020a2

## Your Environment

* Guilds version 3.5.6.0
* MC Version 1.16.5 tuinity

**Comment by darbyjack** [comment]
I believe I have this fixed already in the next update.

**Comment by hkkongou** [comment]
> I believe I have this fixed already in the next update.

where to get next update?
i bought from spigotmc : (

**Comment by darbyjack** [comment]
The next update is almost ready. I have test jars in the Discord!

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/guilds-plugin/Guilds/commit/606a481f2b40e84309b2aef4552f56abe6566578.
