### ISSUE TITLE
add translation option for toggle chat message

### ISSUE THREAD

**Issue by Jeroen123TC** [guilds-plugin/Guilds#488]
can be added a option to translate te follow message: 

https://imgur.com/a/KIcxQ3D

**Comment by VQ9** [comment]
That message is translatable. Like every other one :)
It can be located under 
chat:
  toggled-on: ""

**Comment by darbyjack** [comment]
I believe they are referring to the "GUILD" part of it. That's grabbing from an enum value, which I haven't designed to be translatable.

**Comment by Jeroen123TC** [comment]
Jeah, but can you add the option to translate? I have a dutch server so it would be awesome if its possible. :)

**Comment by darbyjack** [comment]
Pending the PR above getting merged, this will be in the next development build / SpigotMC release.

**Comment by Jeroen123TC** [comment]
Awesome man! Thanks a lot

**Comment by darbyjack** [comment]
For sure! Thanks for letting me know about that! I try to make everything I can translteable within reason.
