### ISSUE TITLE
The plugin doesn't synchronize data from the MYSQL database automatically

### ISSUE THREAD

**Issue by BigCloudsec** [guilds-plugin/Guilds#489]
Hello,
I run this plugin on multiple Bungeecord servers and want the players can create/use the same Guilds system across different servers.

But I found that the plugin doesn't load the data from MYSQL automatically, it only synchronizes from the database when I execute command /guilds reload or reboot the entire server. **This means players can create Guilds with the same name at different servers if I don't reload the plugin constantly.**

Below is the configuration I'm using

storage:
    # What storage method should be used? (MySQL, MariaDB, JSON, SQLite)
    storage-type: MySQL
    # How often (in minutes) do you want all Guild Data to save?
    save-interval: 0
    sql:
        # Define the address for the database. (Doesn't apply to SQLite)
        host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        # Define the port for the database. (Doesn't apply to SQLite)
        port: 'xxxxx'
        # The name of the database to store data in.
        # This must be already created! (Doesn't apply to SQLite)
        database: guilds
        # The prefix for all Guilds tables.
        table-prefix: guilds_
        # Define the credentials for the database. (Doesn't apply to SQLite)
        username: root
        password: xxxxxxxxxxxxxxxxxxxxxxxxx
        # Sets whether or not to use SSL for the remote SQL database connection (Doesn't apply to SQLite)
        enable-ssl: false
        # These settings change the SQL connection pool.
        # The default settings are optimized for the majority of users.
        # Do NOT change these settings unless you know what you are doing!
        # For those looking to migrate data:
        # IF YOU ARE MIGRATING FROM JSON OR SQLITE TO MYSQL THE SETTINGS MUST BE CONFIGURED EVEN IF THE DATA TYPE IS SET TO JSON OR MYSQL.
        # When migrating to MySQL, it will attempt to use the MySQL backend (grab the login information here) in order to connect to the database.
        # We are not responsible for data loss if you are too lazy to read the warnings.
        # ALWAYS REMEMBER TO BACKUP DATA BEFORE MIGRATING.
        # Lastly, remember to change your storage-type to the type you're migrating to before you reboot.
        pool:
            # Sets the maximum size of the SQL connection pool.
            # This value will determine the maximum number of connections maintained. (Doesn't apply to SQLite)
            maximum-pool-size: 10
            # Sets the minimum number of idle connections that the pool will maintain.
            # For maximum performance keep this value the same as 'maximum-pool-size' (Doesn't apply to SQLite)
            minimum-idle: 10
            # Sets the maximum lifetime of a connection in the pool in milliseconds. (Doesn't apply to SQLite)
            maximum-lifetime: 1800000
            # Sets the maximum number of milliseconds for a connection in the pool before timing out. (Doesn't apply to SQLite)
            connection-timeout: 50000

**Comment by darbyjack** [comment]
The plugin is not designed to sync across servers. See https://github.com/guilds-plugin/Guilds/issues/295.
