### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.trim()" because "<local5>" is null

### ISSUE THREAD

**Issue by hkkongou** [guilds-plugin/Guilds#490]
## Description
Error show up when guild is loading
i can reproduce in one of my server computer but not my another server computer tho
this error does not affect anything, plugin can still load, but i didn't test any other functions yet so not sure will this actually breaking something

![image](https://user-images.githubusercontent.com/61608872/129650451-46086551-04a8-4e29-adf8-86edad34deba.png)

## Expected Behavior
no error
## Actual Behavior
have error

## Possible Fix
i don't know

## Steps to Reproduce

1. start up server

## Context
not sure what will it do

## Your Environment

* Guilds version 3.5.6.1
* MC Version 1.16.5

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/guilds-plugin/Guilds/commit/521710e8868419d7f81c4fd5002d95d8801a682d
