### ISSUE TITLE
[BUG] when change page-info 

### ISSUE THREAD

**Issue by kedavlar** [guilds-plugin/Guilds#494]
Hi, i recently buy guild and when i try to traslate the option: page-info in the file and reload pl or restart the server, any translation or writing I put in it is not updated. 

GUILD version: 3.5.6.1
server: tuinity 1.16.5

**Comment by darbyjack** [comment]
This does not provide me any useful information. There's a template for a reason. Open a new ticket and give me reproduction steps, images also help.
