### ISSUE TITLE
[BUG] page-info

### ISSUE THREAD

**Issue by kedavlar** [guilds-plugin/Guilds#495]
## Description
in translations when the option: page-info is changed, it is not saved even if the server or the plugin is restarted

## Expected Behavior
translation saved

## Actual Behavior
the translation is not saved in any way

## Possible Fix
.

## Steps to Reproduce
1. Change page-info in translaction
2. reload pl or restart rerver
3. nothing append

## Context
I want to customize everything

## Your Environment
* Guilds version: 3.5.6.1
* MC Version: 1.16.5 tuinity

EDIT: the translation file is also reset to default.

**Comment by darbyjack** [comment]
This looks more like something that's in the command library instead of the plugin itself. I don't have much control over the command library so this might be a limitation that I can't allow configuration of for the time being. Thank you for your understanding.
