### ISSUE TITLE
[BUG] war

### ISSUE THREAD

**Issue by kedavlar** [guilds-plugin/Guilds#496]
## Description
when someone sends a war request to another guild and one of the two guilds does not enter after accepting the war, does not use the / g war join command to enter hold, when time runs out the challenge remains pending and cannot be canceled so that none of the 2 guilds can not make more wars.

## Expected Behavior
the war ends, allowing us to make another one

## Actual Behavior
wars are no longer possible

## Possible Fix
.

## Steps to Reproduce
1. do /g war challenge '' ''
2. and accept with /g war accept
3. dont use /g war join and let the timer finish
4. after the fail, its impossible to do another war

## Context
.

## Your Environment
Guilds version: 3.5.6.1
MC Version: 1.16.5 tuinity

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/commit/5e39c95fc6a395c210578231d410f1ac96f24402
