### ISSUE TITLE
The permission “guilds.ffa.guild” Doesn’t work

### ISSUE THREAD

**Issue by Jeroen123TC** [guilds-plugin/Guilds#505]
I put the permssion: guilds.ffa.guild, to a single world. So players can have in that world duels an global pvp. 
But players from the same Guild can’t hit each other.  I also put the permission to the player them selfs but that doesn’t work either. The normal pvp works fine, i have tested it.

* Guilds version: 3.5.6.1
* MC Version: 1.17.1
* Permission plugin: Networkmanager

**Comment by darbyjack** [comment]
This one is a slight typo on mine. Somehow this slipped through the release. The permission is actually `guilds.ffa` instead of `guilds.ffa.guild`. I plan to update it to the latter at some point.
