### ISSUE TITLE
Message doesnt change.

### ISSUE THREAD

**Issue by oqo0** [guilds-plugin/Guilds#516]
## Description

We use Russian transtaltion and trying to change help.page-info message, but it doesnt work.
## Expected Behavior

We tried doing something like this:
  page-info: <c1>&7Страница</c1> <c2>&6{page}</c2> &7из <c2>&6{totalpages}</c2> &7(<c3>&6{results}</c3> <c1>&7результатов).</c1>
## Actual Behavior

 But it still doesnt work. Message does not get changed. (It stays as a default message for russian translation)

## Your Environment

Guilds 3.5.6.1
Paper 1.12.2

**Comment by darbyjack** [comment]
What happens if you try page_info?
