### ISSUE TITLE
Guild war bug

### ISSUE THREAD

**Issue by oqo0** [guilds-plugin/Guilds#521]
## Description
If one of the guilds does not have enough joined people to start a guild war, then both guilds get stuck in the war state and cannot start a new war or cancel it until the server is restarted.

## Expected Behavior
If the guild does not have enough joined people to start a war, then the war should be canceled and both rival guilds should be able to start a war again.

## Actual Behavior
If the guild does not have enough joined people to start a war, then both rival guilds cannot start a new war, but must wait for the server to restart.

## Steps to Reproduce
1. Set `war.min-players` for 2 or more.
2. Send a war request to another guild.
3. 2 people from the rival guild join a war. Only 1 person from your guild enters the war.
4. After the end of the `accept-time` guilds war gets bugged. (Players from both guilds cannot start a new war until the server is restarted.)

## Context
Players cannot normally participate in guilds wars, wars always get bugged and players have to wait 24 hours to start a new war.

## Environment
Guilds 3.5.6.1
Paper 1.12.2

**Comment by darbyjack** [comment]
This should have been fixed via https://github.com/guilds-plugin/Guilds/commit/5e39c95fc6a395c210578231d410f1ac96f24402 . Can you confirm it still works in the latest commit?

**Comment by oqo0** [comment]
Good.
