### ISSUE TITLE
cant see all players in guild

### ISSUE THREAD

**Issue by cnluminous** [guilds-plugin/Guilds#637]
## Description

guild player list can't next page
## Expected Behavior

Players can turn pages when exceeding the current GUI display
## Actual Behavior

can see more players in the guild
## Possible Fix

none
## Steps to Reproduce

1. /guild list
2.select guild

## Context

For players, they cannot see all the members of the guild, only 42 members can be seen

## Your Environment

* Guilds version 3.5.6.6
* MC Version Paper1.19.2-142
* Plugin List
* I don't think it's necessary. It's just a design flaw

**Comment by darbyjack** [comment]
Definitely a design flaw! I will see if I can get this paginated.

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/guilds-plugin/Guilds/commit/a2e2cfec068a0088ad811be9ea29d386b076e669
