### ISSUE TITLE
Cannot resolve symbol 'GuildsAPI'

### ISSUE THREAD

**Issue by WMGameLive** [guilds-plugin/Guilds#639]
## Description

I am developing a plugin, I want to hook into the Guilds API.
https://wiki.helpch.at/glares-plugins/guilds-w.i.p-migration/developer-api
I followed this, but I can't import the "GuildsAPI", it said "Cannot resolve symbol 'GuildsAPI'".
I am using 3.5.6.6.

**Comment by darbyjack** [comment]
That is odd. I seem to be able to resolve it on my end. Can you see if any of these other versions work? 

https://repo.glaremasters.me/#browse/browse:guilds:me%2Fglaremasters%2Fguilds

Can I also see your gradle / pom file?

**Comment by WMGameLive** [comment]
3.5.6.5 still not work, but 3.5.6.0 is work.

my pom file:
https://paste.gg/p/anonymous/4735a43115214ba0bb77f1546f12d47d

**Comment by darbyjack** [comment]
Gotcha. Luckily not much has changed between those versions, so you shouldn't be missing out on too much. I'll see if I can figure out the problem. Worst-case scenario you can just compile the jar and use it in your POM :)
