### ISSUE TITLE
EssentialsX Invalid format

### ISSUE THREAD

**Issue by cnluminous** [guilds-plugin/Guilds#649]
## Description

EssentialsX Invalid format
## Expected Behavior

essentialsX chat config:
format: '[&b{WORLDNAME}&7][{GUILD_PREFIX}&7][{PREFIX}&7]&r{NICKNAME} > {MESSAGE}'

should be {GUILD_PREFIX} see guild prefix,but it dont show,I tested all variables and found them invalid
## Actual Behavior

to Expected Behavior
## Possible Fix

idk
## Steps to Reproduce

1.nope

## Context

players dont show guild name 

## Your Environment

* Guilds version 3.5.6.8
* MC Version 1.19.4
* Plugin List 
*  *7yPay, *7yPayGui, Citizens, CMILib, CoreProtect, DeluxeMenus, Essentials, EssentialsSpawn, ExcellentCrates, Floatingmarket,Guilds, ,Kook, LuckPerms, NexEngine, OpenInv, PlaceholderAPI, PlayerPoints, PlotSquared, PlugManX, ProtocolLib, QuickShop, Residence, TrChat(This is the current replacement essentialsx chat plugin), Vault, VipCenter, WorldEdit

**Comment by darbyjack** [comment]
You don't have EssentialsChat.

**Comment by wolfebersahd** [comment]
TrChat is not EssentialsChat

**Comment by cnluminous** [comment]
Because I have already deleted him and used trchat as a temporary replacement

**Comment by wolfebersahd** [comment]
Well typically when you report an issue you list the plugins that you had on your server when you had the issue. Not after you removed it.

The only thing I can think of is that you didn't enable the essentials hook in the Guilds config.

```yml
hooks:
    # Do we want to hook into Essentials-Chat format to handle guild placeholders?
    essentials-chat: false```

**Comment by wolfebersahd** [comment]
I've been using a guilds for years now, that option has always been there.

**Comment by cnluminous** [comment]
ok ,thanks.
