### ISSUE TITLE
Some commands show staff names even if they are in vanish

### ISSUE THREAD

**Issue by hotspuraz** [guilds-plugin/Guilds#650]
## Description
Some commands list all online players' names when you use them, even operators in vanish and staff using other vanish plugins.
![image](https://user-images.githubusercontent.com/38726257/233710524-7cba3d32-f2d2-4423-8fb3-82050f60651e.png)

## Expected Behavior
Vanished players should be treated the same as offline players, and commands like /guild invite or /guild war challenge should say the player is offline.

## Actual Behavior
Several commands will send messages to the player that either directly tell them via a list of names or send them a message which suggests that the player is online. 

## Possible Fix
![image](https://user-images.githubusercontent.com/38726257/233710636-f855449f-c36c-4a31-919e-5ee3165b5b7b.png)

## Steps to Reproduce
Using a plugin like VelocityVanish, put a player into vanish and then on another account use `/clan invite <name>` and it will invite them. If you use the name of someone who is offline then it will give you a list of players online, including those in vanish.

## Context
This is highly abusable by players, especially ones looking to cheat on the server.

## Your Environment

* Guilds-3.5.6.5
* git-Matter-23: 1.19.2
* Guilds & VelocityVanish

**Comment by darbyjack** [comment]
I believe this was fixed via https://github.com/guilds-plugin/Guilds/commit/8c8348e9328576e5da72b2b022289dc5dfb9f9ec
