### ISSUE TITLE
Guild Vault - Blacklist items

### ISSUE THREAD

**Issue by madtomic** [guilds-plugin/Guilds#97]
Blacklist items with materials/custom name or custom lore.

Custom name or lore is prefer.

**Comment by madtomic** [comment]
Any update regarding to this request?

**Comment by darbyjack** [comment]
Hey there,

I have actually been actively considering how to implement this feature. I'm fairly sure I'll have an idea soon for it. It'll probably be by the name of the item so you can input color names and what. Lores might be a little bit of an issue.

**Comment by darbyjack** [comment]
#134 has implemented this.
